export type Locale = 'fr' | 'en';

export const defaultLocale: Locale = 'fr';
export const locales: Locale[] = ['fr', 'en'];

export const kidsCategories = [
  'animaux',
  'animaux-marins',
  'ferme',
  'vehicules',
  'nature',
  'alphabet',
  'dinosaures',
  'super-heros',
  'espace',
  'princesses-chevaliers',
  'metiers',
  'sport',
  'saisons',
  'fetes',
  'personnages',
  'contes',
  'drole',
  'musique',
  'nourriture',
  'pirates',
  'robots',
] as const;

export const adultCategories = [
  'mandalas',
  'mosaiques',
  'abstrait',
  'cartes',
  'paysages',
] as const;

export const categories = [...kidsCategories, ...adultCategories] as const;

export type Category = (typeof categories)[number];

const translations: Record<string, Record<Locale, string>> = {
  'site.title': {
    fr: 'Colotopia — Coloriages Gratuits à Imprimer',
    en: 'Colotopia — Free Printable Coloring Pages',
  },
  'site.description': {
    fr: 'Colotopia : des centaines de coloriages gratuits à imprimer pour les enfants et les adultes. Animaux, véhicules, mandalas, mosaïques et plus encore !',
    en: 'Colotopia: hundreds of free printable coloring pages for kids and adults. Animals, vehicles, mandalas, mosaics and more!',
  },
  'nav.home': { fr: 'Accueil', en: 'Home' },
  'nav.categories': { fr: 'Catégories', en: 'Categories' },
  'audience.enfants': { fr: 'Enfants', en: 'Kids' },
  'audience.adultes': { fr: 'Adultes', en: 'Adults' },
  'category.animaux': { fr: 'Animaux', en: 'Animals' },
  'category.animaux-marins': { fr: 'Animaux Marins', en: 'Sea Animals' },
  'category.ferme': { fr: 'Ferme', en: 'Farm' },
  'category.vehicules': { fr: 'Véhicules', en: 'Vehicles' },
  'category.nature': { fr: 'Nature', en: 'Nature' },
  'category.alphabet': { fr: 'Alphabet', en: 'Alphabet' },
  'category.dinosaures': { fr: 'Dinosaures', en: 'Dinosaurs' },
  'category.super-heros': { fr: 'Super-héros', en: 'Superheroes' },
  'category.espace': { fr: 'Espace', en: 'Space' },
  'category.princesses-chevaliers': { fr: 'Princesses & Chevaliers', en: 'Princesses & Knights' },
  'category.metiers': { fr: 'Métiers', en: 'Jobs' },
  'category.sport': { fr: 'Sport', en: 'Sport' },
  'category.saisons': { fr: 'Saisons', en: 'Seasons' },
  'category.fetes': { fr: 'Fêtes', en: 'Holidays' },
  'category.mandalas': { fr: 'Mandalas', en: 'Mandalas' },
  'category.mosaiques': { fr: 'Mosaïques', en: 'Mosaics' },
  'category.abstrait': { fr: 'Abstrait', en: 'Abstract' },
  'category.cartes': { fr: 'Cartes', en: 'Maps' },
  'category.personnages': { fr: 'Personnages', en: 'Characters' },
  'category.contes': { fr: 'Contes', en: 'Fairy Tales' },
  'category.drole': { fr: 'Drôle', en: 'Funny' },
  'category.musique': { fr: 'Musique', en: 'Music' },
  'category.nourriture': { fr: 'Nourriture', en: 'Food' },
  'category.pirates': { fr: 'Pirates', en: 'Pirates' },
  'category.robots': { fr: 'Robots', en: 'Robots' },
  'category.paysages': { fr: 'Paysages', en: 'Landscapes' },
  'coloring.download': { fr: 'Télécharger le PDF', en: 'Download PDF' },
  'coloring.print': { fr: 'Imprimer', en: 'Print' },
  'footer.rights': {
    fr: 'Tous droits réservés',
    en: 'All rights reserved',
  },
  'footer.kids': { fr: 'Coloriages Enfants', en: 'Kids Coloring' },
  'footer.adults': { fr: 'Coloriages Adultes', en: 'Adult Coloring' },
  'footer.legal': { fr: 'Informations', en: 'Information' },
  'footer.privacy': { fr: 'Politique de confidentialité', en: 'Privacy Policy' },
  'footer.terms': { fr: "Conditions d'utilisation", en: 'Terms of Use' },
  'footer.contact': { fr: 'Contact', en: 'Contact' },
  'share.label': { fr: 'Partager', en: 'Share' },
  'share.whatsapp': { fr: 'Partager sur WhatsApp', en: 'Share on WhatsApp' },
  'share.facebook': { fr: 'Partager sur Facebook', en: 'Share on Facebook' },
  'share.pinterest': { fr: 'Épingler sur Pinterest', en: 'Pin on Pinterest' },
  'legal.privacy.title': { fr: 'Politique de confidentialité', en: 'Privacy Policy' },
  'legal.terms.title': { fr: "Conditions d'utilisation", en: 'Terms of Use' },
  'home.hero.subtitle': {
    fr: 'Des centaines de coloriages originaux pour les enfants. Téléchargez, imprimez et coloriez !',
    en: 'Hundreds of original coloring pages for kids. Download, print and color!',
  },
  'home.empty': {
    fr: 'Les coloriages arrivent bientôt ! Revenez nous voir.',
    en: 'Coloring pages coming soon! Check back later.',
  },
  'category.description': {
    fr: 'Découvrez nos coloriages {label} gratuits à imprimer.',
    en: 'Discover our free printable {label} coloring pages.',
  },
  'category.empty': {
    fr: 'Les coloriages {label} arrivent bientôt !',
    en: '{label} coloring pages coming soon!',
  },
  'categories.title': {
    fr: 'Toutes les Catégories',
    en: 'All Categories',
  },
  'categories.description': {
    fr: 'Parcourez toutes nos catégories de coloriages gratuits à imprimer.',
    en: 'Browse all our free printable coloring page categories.',
  },
  'categories.count': {
    fr: '{count} coloriages',
    en: '{count} coloring pages',
  },
  'categories.explore': {
    fr: 'Voir les coloriages',
    en: 'View coloring pages',
  },
  'home.nouveaux.title': {
    fr: 'Nouveaux Coloriages',
    en: 'New Coloring Pages',
  },
  'home.nouveaux.subtitle': {
    fr: 'Les derniers ajoutés',
    en: 'Latest additions',
  },
  'home.filter.all': { fr: 'Tous', en: 'All' },
  'category.description.adults': {
    fr: 'Découvrez nos coloriages {label} gratuits à imprimer pour adultes.',
    en: 'Discover our free printable {label} coloring pages for adults.',
  },
  'category.animaux-marins.seoText': {
    fr: '<h2>Coloriages animaux marins gratuits à imprimer</h2><p>Plongez dans les fonds marins avec nos coloriages animaux marins ! Pieuvres aux tentacules ondulants, hippocampes majestueux, baleines géantes, requins souriants, méduses lumineuses — notre collection vous invite à explorer la vie sous-marine. Parfait pour apprendre aux enfants à connaître les créatures des océans tout en s\'amusant à colorier. Chaque dessin est simple, cute et adapté aux enfants de 3 à 10 ans.</p>',
    en: '<h2>Free sea animal coloring pages to print</h2><p>Dive into the ocean depths with our sea animal coloring pages! Octopuses with waving tentacles, majestic seahorses, giant whales, smiling sharks, glowing jellyfish — our collection invites you to explore underwater life. Perfect for teaching children about ocean creatures while having fun coloring. Each drawing is simple, cute and suitable for children aged 3 to 10.</p>',
  },
  'category.ferme.seoText': {
    fr: '<h2>Coloriages animaux de la ferme gratuits</h2><p>La vie à la ferme en coloriages ! Vaches tachetées, moutons laineux, cochons roses, poules et leurs poussins, canards sur la mare — nos coloriages ferme font découvrir aux enfants les animaux domestiques et la vie rurale. Idéal pour les petits qui découvrent les animaux et les plus grands qui aiment colorier des scènes champêtres. Des dessins attachants avec le tracteur, la grange rouge et les animaux adorables à colorier.</p>',
    en: '<h2>Free farm animal coloring pages to print</h2><p>Farm life in coloring pages! Spotted cows, fluffy sheep, pink pigs, hens with their chicks, ducks on the pond — our farm coloring pages introduce children to domestic animals and rural life. Perfect for little ones discovering animals and older children who enjoy coloring countryside scenes. Charming drawings featuring tractors, red barns, and adorable animals to color.</p>',
  },
  'category.animaux.seoText': {
    fr: '<h2>Coloriages animaux gratuits à imprimer</h2><p>Les coloriages animaux sont parmi les plus appréciés de notre collection. Que votre enfant soit passionné par les <a href="/fr/coloriage/animaux-lion">lions</a> de la savane, les <a href="/fr/coloriage/animaux-dauphin">dauphins</a> des océans ou les <a href="/fr/coloriage/animaux-lapin">lapins</a> de la maison, vous trouverez ici des dizaines de modèles à imprimer gratuitement. Notre sélection couvre l\'ensemble du règne animal : animaux sauvages d\'Afrique et d\'Asie (<a href="/fr/coloriage/animaux-elephant">éléphants</a>, tigres, girafes, rhinocéros), animaux de la ferme (vaches, cochons, poules, chevaux), animaux domestiques (<a href="/fr/coloriage/animaux-chat">chats</a>, chiens, lapins, perroquets) et créatures marines (dauphins, requins, tortues marines, étoiles de mer).</p><h2>Apprendre en coloriant les animaux</h2><p>Colorier des animaux présente de nombreux avantages pédagogiques : les enfants apprennent à reconnaître les espèces, découvrent leurs habitats naturels et développent leur sensibilité à la nature et à la biodiversité. C\'est aussi une activité ludique qui renforce la concentration et améliore la motricité fine. Les grands peuvent choisir des coloriages plus détaillés avec les textures des plumes, des écailles ou de la fourrure. Les petits apprécieront des dessins aux contours simples et aux formes rondes. Tous nos coloriages animaux sont disponibles au format A4, imprimables gratuitement depuis n\'importe quel appareil. Imprimez-les pour des activités à la maison, en classe ou lors d\'ateliers créatifs en famille.</p>',
    en: '<h2>Free printable animal coloring pages</h2><p>Animal coloring pages are among the most popular in our collection, loved by children of all ages. Whether your child is fascinated by <a href="/en/coloring/animals-lion">lions</a> on the savanna, <a href="/en/coloring/animals-dolphin">dolphins</a> in the ocean, or the family <a href="/en/coloring/animals-dog">dog</a> at home, you\'ll find dozens of free printable illustrations here. Our selection covers the entire animal kingdom: wild animals from Africa and Asia (<a href="/en/coloring/animals-elephant">elephants</a>, tigers, giraffes, rhinos), farm animals (cows, pigs, chickens, horses), domestic pets (<a href="/en/coloring/animals-cat">cats</a>, dogs, rabbits, parrots), and sea creatures (dolphins, sharks, sea turtles, starfish).</p><h2>Learning through animal coloring</h2><p>Coloring animals offers multiple educational benefits: children learn to recognize and name species, discover their natural habitats, and develop a love for nature and biodiversity. It\'s also a fun activity that strengthens concentration and improves fine motor skills. Older children can choose more detailed illustrations featuring feather textures, scales, or fur patterns. Younger ones will enjoy drawings with simple outlines and rounded shapes. All our animal coloring pages are available in A4 format, free to print from any device. Print them for home activities, classroom workshops, or creative family outings.</p>',
  },
  'category.vehicules.seoText': {
    fr: '<h2>Coloriages véhicules gratuits à imprimer</h2><p><a href="/fr/coloriage/vehicules-voiture">Voitures</a> de course, <a href="/fr/coloriage/vehicules-camion-pompier">camions de pompier</a>, <a href="/fr/coloriage/vehicules-avion">avions</a> à réaction, vaisseaux spatiaux — notre collection de coloriages véhicules ravira tous les enfants passionnés de machines et de transport. Chaque coloriage est dessiné avec précision pour représenter fidèlement les détails de chaque véhicule tout en restant accessible aux jeunes coloristes. Nos catégories couvrent l\'ensemble des modes de transport : la route (voitures, camions, <a href="/fr/coloriage/vehicules-moto">motos</a>, bus, taxis), le rail (<a href="/fr/coloriage/vehicules-train">trains</a> à vapeur, TGV, tramways, métros), les airs (avions de ligne, <a href="/fr/coloriage/vehicules-helicoptere">hélicoptères</a>, montgolfières) et la mer (bateaux à voile, paquebots, sous-marins). Sans oublier les véhicules spéciaux : ambulances, camions de pompier, tracteurs agricoles et engins de chantier que les enfants adorent.</p><h2>Apprendre les transports en coloriant</h2><p>Colorier des véhicules est une excellente activité pour développer la motricité fine et la concentration. C\'est aussi une porte d\'entrée vers l\'apprentissage : comment fonctionne un moteur ? Quelle est la différence entre un avion et un hélicoptère ? Les enfants apprennent en jouant. Nos coloriages véhicules sont disponibles gratuitement en format A4 haute résolution, prêts à imprimer en un clic. Parfaits pour les anniversaires sur le thème des voitures, les activités scolaires ou simplement pour occuper les enfants lors de longs trajets.</p>',
    en: '<h2>Free printable vehicle coloring pages</h2><p><a href="/en/coloring/vehicles-car">Race cars</a>, <a href="/en/coloring/vehicles-fire-truck">fire trucks</a>, <a href="/en/coloring/vehicles-airplane">jet planes</a>, space shuttles — our vehicle coloring pages will delight every child passionate about machines and transportation. Each illustration is drawn with precision to faithfully represent the details of each vehicle while remaining accessible to young artists. Our categories cover all modes of transport: road (cars, trucks, <a href="/en/coloring/vehicles-motorcycle">motorcycles</a>, buses, taxis), rail (steam <a href="/en/coloring/vehicles-train">trains</a>, high-speed trains, trams, subways), air (airliners, <a href="/en/coloring/vehicles-helicopter">helicopters</a>, hot air balloons), and sea (sailboats, cruise ships, submarines, aircraft carriers). Not forgetting special vehicles: ambulances, fire trucks, farm tractors, and construction equipment that children adore.</p><h2>Learning about transportation through coloring</h2><p>Coloring vehicles is an excellent activity for developing fine motor skills and concentration. It\'s also a gateway to learning: how does a motor work? What\'s the difference between a plane and a helicopter? Children learn while having fun. Our vehicle coloring pages are available for free in A4 high-resolution format, ready to print with one click. Perfect for car-themed birthday parties, school activities, or simply keeping children busy during long road trips.</p>',
  },
  'category.nature.seoText': {
    fr: '<h2>Coloriages nature gratuits à imprimer</h2><p>La nature offre une palette de couleurs infinie, et nos coloriages nature en capturent toute la beauté. <a href="/fr/coloriage/nature-fleur">Fleurs</a> des champs, <a href="/fr/coloriage/nature-arbre">arbres</a> centenaires, <a href="/fr/coloriage/nature-champignon">champignons</a> enchantés, paysages de <a href="/fr/coloriage/nature-montagne">montagne</a> : notre collection permet aux enfants d\'explorer et de s\'approprier le monde végétal et naturel. Découvrez des roses et des tournesols pour les amoureux de jardinage, des <a href="/fr/coloriage/nature-foret">forêts</a> mystérieuses pour les amateurs de fantastique, des fonds marins luxuriants pour les explorateurs des <a href="/fr/coloriage/nature-ocean">océans</a>. Nos coloriages nature incluent aussi des scènes de saisons : cerisiers en fleurs du printemps, forêts d\'automne aux tons orangés, plages ensoleillées de l\'été et paysages enneigés de l\'hiver.</p><h2>Sensibiliser les enfants à l\'environnement</h2><p>Colorier la nature sensibilise les enfants à l\'environnement et à la biodiversité. En choisissant les couleurs d\'une fleur ou d\'un arbre, ils apprennent que chaque plante a ses propres couleurs, que les feuilles changent en automne, que les fleurs attirent les abeilles et les papillons. C\'est une éducation à l\'écologie par le dessin. Nos coloriages nature sont gratuits, disponibles au format A4 et prêts à imprimer. Ils conviennent aussi bien aux enfants qu\'aux adultes qui souhaitent se reconnecter à la beauté de la nature par le dessin et la créativité.</p>',
    en: '<h2>Free printable nature coloring pages</h2><p>Nature offers an infinite palette of colors, and our nature coloring pages capture all its beauty. Meadow <a href="/en/coloring/nature-flower">flowers</a>, century-old <a href="/en/coloring/nature-tree">trees</a>, enchanted <a href="/en/coloring/nature-mushroom">mushrooms</a>, <a href="/en/coloring/nature-mountain">mountain</a> landscapes — our collection lets children explore and connect with the plant and natural world. Discover roses and sunflowers for gardening lovers, mysterious <a href="/en/coloring/nature-forest">forests</a> for fantasy fans, lush seabeds for <a href="/en/coloring/nature-ocean">ocean</a> explorers. Our nature coloring pages also include seasonal scenes: spring cherry blossoms, autumn forests in golden and orange tones, sunny summer beaches, and snowy winter landscapes.</p><h2>Raising environmental awareness through coloring</h2><p>Coloring nature raises children\'s awareness of the environment and biodiversity. By choosing the colors of a flower or tree, they learn that each plant has its own colors, that leaves change in autumn, that flowers attract bees and butterflies. It\'s an education in ecology through drawing. Our nature coloring pages are free, available in A4 format, and ready to print. They are suitable for both children and adults who wish to reconnect with the beauty of nature through drawing and creativity.</p>',
  },
  'category.alphabet.seoText': {
    fr: '<h2>Coloriages alphabet éducatifs gratuits</h2><p>Apprendre l\'alphabet devient un jeu d\'enfant avec nos coloriages éducatifs ! Chaque lettre est associée à un dessin amusant qui aide les enfants à mémoriser l\'alphabet tout en s\'amusant. Le <a href="/fr/coloriage/alphabet-a">A</a> comme Ananas, le <a href="/fr/coloriage/alphabet-b">B</a> comme Ballon, le <a href="/fr/coloriage/alphabet-c">C</a> comme Chat — nos coloriages alphabet suivent cette logique mnémotechnique qui facilite l\'apprentissage de la lecture et de l\'écriture. Notre collection propose des coloriages pour toutes les lettres, de A à <a href="/fr/coloriage/alphabet-z">Z</a>, avec des dessins soigneusement choisis pour être immédiatement reconnaissables par les jeunes enfants.</p><h2>Un outil pédagogique pour la maternelle et le CP</h2><p>Les lettres sont tracées en grands caractères, idéales pour que les enfants apprennent aussi à les écrire en les repassant au crayon. Ces coloriages sont des outils pédagogiques précieux pour les parents et les enseignants de maternelle et de CP. Ils permettent d\'associer l\'aspect visuel de chaque lettre à une image mémorable, renforçant ainsi l\'apprentissage de manière durable. En plus de l\'aspect éducatif, colorier les lettres développe la motricité fine, la coordination œil-main et la concentration — des compétences essentielles pour l\'apprentissage scolaire. Tous nos coloriages alphabet sont disponibles gratuitement au format A4. Imprimez-les pour les utiliser à la maison ou en classe, comme support de jeu ou comme exercice d\'écriture.</p>',
    en: '<h2>Free educational alphabet coloring pages</h2><p>Learning the alphabet becomes child\'s play with our educational coloring pages! Each letter is paired with a fun drawing that helps children memorize the alphabet while having fun. <a href="/en/coloring/alphabet-a">A</a> for Apple, <a href="/en/coloring/alphabet-b">B</a> for Ball, <a href="/en/coloring/alphabet-c">C</a> for Cat — our alphabet coloring pages follow this mnemonic logic that makes learning to read and write easier. Our collection offers coloring pages for every letter, from A to <a href="/en/coloring/alphabet-z">Z</a>, with illustrations carefully chosen to be immediately recognizable by young children.</p><h2>A valuable tool for preschool and kindergarten</h2><p>The letters are drawn in large characters, ideal for children to also practice writing by tracing them. These coloring pages are valuable educational tools for parents and preschool and kindergarten teachers. They allow each letter\'s visual form to be associated with a memorable image, reinforcing learning in a lasting way. Beyond the educational aspect, coloring letters develops fine motor skills, hand-eye coordination, and concentration — essential skills for school learning. All our alphabet coloring pages are available for free in A4 format. Print them for use at home or in the classroom, as play supports or writing exercises.</p>',
  },
  'category.dinosaures.seoText': {
    fr: '<h2>Coloriages dinosaures gratuits à imprimer</h2><p>Partez à la conquête du Jurassique avec nos coloriages dinosaures ! Notre collection réunit tous les géants préhistoriques que les enfants adorent : le redoutable <a href="/fr/coloriage/dinosaures-t-rex">Tyrannosaurus Rex</a> aux immenses mâchoires, le long et paisible <a href="/fr/coloriage/dinosaures-diplodocus">Diplodocus</a>, le <a href="/fr/coloriage/dinosaures-triceratops">Tricératops</a> avec ses trois cornes impressionnantes, le <a href="/fr/coloriage/dinosaures-stegosaurus">Stégosaure</a> avec ses plaques dorsales et le <a href="/fr/coloriage/dinosaures-velociraptor">Vélociraptor</a> agile et intelligent. Nos dessins sont réalisés avec précision scientifique tout en restant accessibles aux jeunes artistes. Les enfants peuvent laisser libre cours à leur imagination : les dinosaures étaient-ils verts, bleus, rouges ? Personne ne sait vraiment, alors tout est permis !</p><h2>Découvrir la paléontologie en coloriant</h2><p>Les coloriages dinosaures sont une porte d\'entrée fascinante vers la paléontologie et l\'histoire de la vie sur Terre. En coloriant leur T-Rex préféré, les enfants apprennent que ces créatures gigantesques ont réellement existé il y a des millions d\'années, ouvrant la discussion sur l\'évolution des espèces et les extinctions de masse. Ces coloriages stimulent la curiosité scientifique et le goût pour la découverte du monde naturel. Nos coloriages dinosaures sont disponibles gratuitement en format A4 haute résolution. Imprimez-les pour des activités passionnantes à la maison, en classe ou lors d\'anniversaires sur le thème préhistorique.</p>',
    en: '<h2>Free printable dinosaur coloring pages</h2><p>Embark on a Jurassic adventure with our dinosaur coloring pages! Our collection brings together all the prehistoric giants children love: the fearsome <a href="/en/coloring/dinosaurs-t-rex">Tyrannosaurus Rex</a> with its massive jaws, the long and peaceful <a href="/en/coloring/dinosaurs-diplodocus">Diplodocus</a>, the <a href="/en/coloring/dinosaurs-triceratops">Triceratops</a> with its three impressive horns, the <a href="/en/coloring/dinosaurs-stegosaurus">Stegosaurus</a> with its dorsal plates, and the agile, intelligent <a href="/en/coloring/dinosaurs-velociraptor">Velociraptor</a>. Our illustrations are made with scientific accuracy while remaining accessible to young artists. Children can let their imagination run wild — were dinosaurs green, blue, or red? Nobody really knows, so anything goes!</p><h2>Discovering paleontology through coloring</h2><p>Dinosaur coloring pages are a fascinating gateway to paleontology and the history of life on Earth. By coloring their favorite T-Rex, children learn that these gigantic creatures actually existed millions of years ago, opening discussions about evolution and mass extinctions. These pages spark scientific curiosity and a love for exploring the natural world. Our dinosaur coloring pages are available for free in A4 high-resolution format. Print them for exciting activities at home, in the classroom, or for prehistoric-themed birthday parties.</p>',
  },
  'category.super-heros.seoText': {
    fr: '<h2>Coloriages super-héros gratuits à imprimer</h2><p>Enfilez la cape et partez sauver le monde avec nos coloriages super-héros ! Notre collection rassemble des dizaines de héros aux pouvoirs extraordinaires dans des poses d\'action dynamiques : le <a href="/fr/coloriage/super-heros-volant">super-héros volant</a> qui protège la ville depuis les airs, le <a href="/fr/coloriage/super-heros-masque">héros masqué</a> qui escalade les immeubles, la <a href="/fr/coloriage/super-heros-heroine-forte">super-héroïne invincible</a> qui affronte les ennemis. Les costumes colorés, les capes flottantes et les emblèmes distinctifs offrent de nombreuses surfaces à colorier. Les enfants peuvent reproduire les couleurs classiques de leurs archétypes préférés ou inventer de nouvelles tenues pour des héros totalement originaux.</p><h2>Développer la créativité et les valeurs</h2><p>Les coloriages super-héros développent la créativité et l\'imagination tout en permettant aux enfants d\'explorer des thèmes importants comme le courage, la justice et la responsabilité. Créer son propre super-héros — lui inventer un nom, des pouvoirs, une histoire — est une activité narrative riche qui stimule le développement cognitif et émotionnel. Découvrez aussi nos super-héros en <a href="/fr/coloriage/super-heros-equipe">équipe</a> et le <a href="/fr/coloriage/super-heros-robot">super-héros robot</a>. Ces coloriages sont parfaits pour les anniversaires sur le thème des super-héros, les fêtes costumées et les ateliers créatifs en classe. Nos coloriages super-héros sont disponibles gratuitement en format A4 haute résolution. Imprimez-les pour des heures de jeu créatif à la maison ou en groupe.</p>',
    en: '<h2>Free printable superhero coloring pages</h2><p>Put on your cape and save the world with our superhero coloring pages! Our collection features dozens of heroes with extraordinary powers in dynamic action poses: the <a href="/en/coloring/superheroes-flying">flying superhero</a> protecting the city from the air, the <a href="/en/coloring/superheroes-masked">masked hero</a> scaling buildings, the invincible <a href="/en/coloring/superheroes-strong-heroine">superheroine</a> taking on enemies. Colorful costumes, flowing capes, and distinctive emblems provide plenty of surfaces to color. Children can reproduce the classic colors of their favorite archetypes or invent new outfits for completely original heroes.</p><h2>Building creativity and values</h2><p>Superhero coloring pages develop creativity and imagination while allowing children to explore important themes like courage, justice, and responsibility. Creating your own superhero — inventing a name, powers, and backstory — is a rich narrative activity that stimulates cognitive and emotional development. Also discover our <a href="/en/coloring/superheroes-team">superhero team</a> and the <a href="/en/coloring/superheroes-robot">robot superhero</a>. These coloring pages are perfect for superhero-themed birthday parties, costume events, and creative classroom workshops. Our superhero coloring pages are available for free in A4 high-resolution format. Print them for hours of creative play at home or in groups.</p>',
  },
  'category.espace.seoText': {
    fr: '<h2>Coloriages espace gratuits à imprimer</h2><p>Décollage immédiat pour l\'aventure spatiale ! Nos coloriages espace transportent les enfants dans les confins du cosmos, à la rencontre des planètes du <a href="/fr/coloriage/espace-systeme-solaire">système solaire</a>, des étoiles lointaines et des mystérieux <a href="/fr/coloriage/espace-alien">extraterrestres</a>. Explorez <a href="/fr/coloriage/espace-saturne">Saturne</a> et ses anneaux magnifiques, Jupiter et ses tempêtes géantes, <a href="/fr/coloriage/espace-mars">Mars</a> la planète rouge, ou encore la Lune criblée de cratères. Nos dessins représentent aussi les vaisseaux spatiaux, des <a href="/fr/coloriage/espace-navette">navettes</a> de la NASA aux <a href="/fr/coloriage/espace-fusee">fusées</a> futuristes en passant par les rovers martiens, et bien sûr les astronautes en combinaison spatiale flottant dans l\'apesanteur.</p><h2>Découvrir l\'astronomie en coloriant</h2><p>Les coloriages espace sont une formidable introduction à l\'astronomie pour les enfants. En coloriant les planètes, ils apprennent leurs noms, leur ordre dans le système solaire et leurs caractéristiques distinctives. C\'est une façon ludique de découvrir les sciences et de nourrir la curiosité pour l\'univers. Ces coloriages stimulent également l\'imagination : et si des extraterrestres vivaient sur d\'autres planètes ? À quoi ressemblerait une cité sur Mars ? Les questions que soulèvent ces dessins ouvrent de belles discussions parent-enfant. Nos coloriages espace sont disponibles gratuitement en format A4. Imprimez-les pour des activités créatives à la maison, en classe de sciences ou lors de soirées d\'observation des étoiles.</p>',
    en: '<h2>Free printable space coloring pages</h2><p>Immediate takeoff for space adventure! Our space coloring pages transport children to the far reaches of the cosmos, where they\'ll encounter <a href="/en/coloring/space-solar-system">solar system</a> planets, distant stars, and mysterious <a href="/en/coloring/space-alien">aliens</a>. Explore <a href="/en/coloring/space-saturn">Saturn</a> with its magnificent rings, Jupiter with its giant storms, red planet <a href="/en/coloring/space-mars">Mars</a>, and the crater-filled Moon. Our illustrations also feature spacecraft — from <a href="/en/coloring/space-shuttle">shuttles</a> to futuristic <a href="/en/coloring/space-rocket">rockets</a> and Mars rovers — plus astronauts in space suits floating in zero gravity.</p><h2>Discovering astronomy through coloring</h2><p>Space coloring pages are a fantastic introduction to astronomy for children. By coloring the planets, they learn their names, their order in the solar system, and their distinctive features. It\'s a fun way to discover science and fuel curiosity about the universe. These pages also spark imagination: what if aliens lived on other planets? What would a city on Mars look like? The questions these drawings raise open wonderful parent-child conversations. Our space coloring pages are available for free in A4 format. Print them for creative activities at home, in science class, or during stargazing evenings.</p>',
  },
  'category.princesses-chevaliers.seoText': {
    fr: '<h2>Coloriages princesses et chevaliers gratuits</h2><p>Bienvenue dans le monde enchanté des princesses et des chevaliers ! Notre collection de coloriages transporte les enfants dans des royaumes féeriques peuplés de belles <a href="/fr/coloriage/princesses-chevaliers-princesse">princesses</a> courageuses, de vaillants <a href="/fr/coloriage/princesses-chevaliers-chevalier">chevaliers</a>, de <a href="/fr/coloriage/princesses-chevaliers-chateau">châteaux</a> majestueux et de <a href="/fr/coloriage/princesses-chevaliers-dragon">dragons</a> cracheurs de feu. Les princesses de notre collection ont chacune leur personnalité unique : guerrière intrépide, magicienne érudite ou diplomate qui négocie la paix entre royaumes. Les chevaliers affrontent dragons et sorciers pour accomplir des quêtes épiques et protéger leurs amis.</p><h2>Inventer des aventures fantastiques</h2><p>Ces coloriages permettent aux enfants de donner vie à des histoires fantastiques. En choisissant les couleurs de la robe d\'une princesse ou de l\'armure d\'un chevalier, ils construisent des personnages et inventent leurs propres aventures. Découvrez aussi notre <a href="/fr/coloriage/princesses-chevaliers-licorne">licorne</a> et notre <a href="/fr/coloriage/princesses-chevaliers-fee">fée</a> enchantée. C\'est une activité qui développe la créativité narrative et l\'imagination. Les dessins aux lignes claires et aux détails soignés conviennent aux enfants de 4 à 10 ans. Les plus jeunes apprécieront les contours simples, tandis que les plus grands pourront s\'amuser à colorier les ornements complexes des costumes et les décors des châteaux. Nos coloriages princesses et chevaliers sont disponibles gratuitement au format A4. Parfaits pour des anniversaires thématiques ou des activités créatives en famille.</p>',
    en: '<h2>Free printable princess and knight coloring pages</h2><p>Welcome to the enchanted world of princesses and knights! Our coloring collection transports children to magical kingdoms filled with brave <a href="/en/coloring/princesses-knights-princess">princesses</a>, valiant <a href="/en/coloring/princesses-knights-knight">knights</a>, majestic <a href="/en/coloring/princesses-knights-castle">castles</a>, and fire-breathing <a href="/en/coloring/princesses-knights-dragon">dragons</a>. The princesses in our collection each have their own unique personality: the fearless warrior, the learned sorceress, or the diplomat who negotiates peace between kingdoms. Knights face dragons and sorcerers to accomplish epic quests and protect their friends.</p><h2>Inventing fantastic adventures</h2><p>These coloring pages allow children to bring fantastic stories to life. By choosing the colors for a princess\'s gown or a knight\'s armor, they build characters and invent their own adventures. Also discover our <a href="/en/coloring/princesses-knights-unicorn">unicorn</a> and enchanted <a href="/en/coloring/princesses-knights-fairy">fairy</a>. It\'s an activity that develops narrative creativity and imagination. Illustrations with clear lines and careful details suit children ages 4 to 10. Younger children will enjoy simple outlines, while older ones can have fun coloring the intricate ornaments of costumes and castle decorations. Our princess and knight coloring pages are available for free in A4 format. Perfect for themed birthday parties or creative family activities.</p>',
  },
  'category.metiers.seoText': {
    fr: '<h2>Coloriages métiers gratuits à imprimer</h2><p>Nos coloriages métiers aident les enfants à découvrir la diversité des professions et à explorer leurs envies de futur. <a href="/fr/coloriage/metiers-pompier">Pompier</a> courageux, <a href="/fr/coloriage/metiers-medecin">médecin</a> attentionné, <a href="/fr/coloriage/metiers-cuisinier">chef cuisinier</a> créatif, <a href="/fr/coloriage/metiers-architecte">architecte</a> visionnaire, <a href="/fr/coloriage/metiers-astronaute">astronaute</a> explorateur : notre collection présente des dizaines de métiers sous forme de dessins attractifs à colorier. Chaque coloriage illustre un professionnel en action avec les outils typiques de son métier : la hache et le casque du pompier, le stéthoscope du médecin, la toque et la spatule du cuisinier, l\'équerre et le compas de l\'architecte.</p><h2>Éveiller les vocations par le coloriage</h2><p>Ces coloriages ont une vraie valeur éducative : ils permettent d\'initier des conversations sur les métiers, l\'importance de chaque rôle dans la société et les formations nécessaires. C\'est une façon ludique d\'éveiller les vocations et de valoriser tous les corps de métier, des plus connus aux moins visibles. Les jeux de rôle autour de ces coloriages — jouer au médecin, au pompier, au chef — renforcent l\'apprentissage et favorisent le développement social et émotionnel des enfants. Nos coloriages métiers sont disponibles gratuitement au format A4. Idéaux pour les activités de classe sur les professions ou les jeux de rôle éducatifs à la maison.</p>',
    en: '<h2>Free printable job coloring pages</h2><p>Our job coloring pages help children discover the diversity of professions and explore their dreams for the future. Brave <a href="/en/coloring/jobs-firefighter">firefighter</a>, caring <a href="/en/coloring/jobs-doctor">doctor</a>, creative <a href="/en/coloring/jobs-chef">chef</a>, visionary <a href="/en/coloring/jobs-architect">architect</a>, exploring <a href="/en/coloring/jobs-astronaut">astronaut</a> — our collection features dozens of jobs as attractive coloring illustrations. Each page depicts a professional in action with the typical tools of their trade: the axe and helmet of the firefighter, the doctor\'s stethoscope, the chef\'s toque and spatula, the architect\'s square and compass.</p><h2>Sparking career dreams through coloring</h2><p>These coloring pages have real educational value: they open conversations about careers, the importance of each role in society, and the education required. It\'s a fun way to spark vocational interest and celebrate all professions, from the most well-known to the less visible. Role-playing games around these pages — playing doctor, firefighter, or chef — reinforce learning and support children\'s social and emotional development. Our job coloring pages are available for free in A4 format. Ideal for classroom activities about careers or educational role-playing games at home.</p>',
  },
  'category.sport.seoText': {
    fr: '<h2>Coloriages sport gratuits à imprimer</h2><p>Le sport, c\'est l\'aventure, le dépassement de soi et le plaisir en équipe ! Nos coloriages sport célèbrent toutes les disciplines sportives que les enfants pratiquent et admirent. <a href="/fr/coloriage/sport-football">Football</a>, <a href="/fr/coloriage/sport-natation">natation</a>, <a href="/fr/coloriage/sport-tennis">tennis</a>, <a href="/fr/coloriage/sport-velo">cyclisme</a>, <a href="/fr/coloriage/sport-gym">gymnastique</a>, basketball, judo, rugby : notre collection couvre un large éventail de sports pour que chaque enfant trouve son activité préférée à colorier. Nos dessins mettent en scène des athlètes en pleine action : le footballeur qui marque un but, la gymnaste qui effectue un saut périlleux, le nageur qui plonge dans la piscine, le cycliste qui dévale une descente.</p><h2>Le sport et les grands événements</h2><p>Ces images dynamiques donnent de l\'énergie et encouragent les enfants à pratiquer des activités physiques. Les coloriages sport peuvent aussi accompagner les grands événements sportifs. Pendant la Coupe du Monde, les Jeux Olympiques ou le Tour de France, imprimez les dessins correspondants pour créer de l\'enthousiasme et des activités créatives en lien avec l\'actualité. C\'est une façon ludique d\'initier les enfants à ces événements mondiaux et aux valeurs du sport : effort, fair-play, persévérance et esprit d\'équipe. Nos coloriages sport sont disponibles gratuitement en format A4. Parfaits pour les associations sportives, les écoles ou simplement pour les familles qui partagent leur passion pour le sport.</p>',
    en: '<h2>Free printable sport coloring pages</h2><p>Sport is adventure, self-improvement, and team fun! Our sport coloring pages celebrate all the athletic disciplines children practice and admire. <a href="/en/coloring/sport-soccer">Soccer</a>, <a href="/en/coloring/sport-swimming">swimming</a>, <a href="/en/coloring/sport-tennis">tennis</a>, <a href="/en/coloring/sport-cycling">cycling</a>, <a href="/en/coloring/sport-gymnastics">gymnastics</a>, basketball, judo, rugby — our collection covers a wide range of sports so every child finds their favorite activity to color. Our illustrations depict athletes in full action: the soccer player scoring a goal, the gymnast performing a somersault, the swimmer diving into the pool, the cyclist racing down a descent.</p><h2>Sports and major events</h2><p>These dynamic images are energizing and encourage children to be physically active. Sport coloring pages can also accompany major sporting events. During the World Cup, the Olympics, or the Tour de France, print the corresponding illustrations to create excitement and creative activities tied to current events. It\'s a fun way to introduce children to these world events and the values of sport: effort, fair play, perseverance, and team spirit. Our sport coloring pages are available for free in A4 format. Perfect for sports clubs, schools, or simply families who share a passion for sports.</p>',
  },
  'category.saisons.seoText': {
    fr: '<h2>Coloriages saisons gratuits à imprimer</h2><p>Les quatre saisons offrent une ronde de couleurs et d\'ambiances tout au long de l\'année. Nos coloriages saisons capturent la magie de chaque période : les <a href="/fr/coloriage/saisons-printemps-fleurs">fleurs du printemps</a>, les <a href="/fr/coloriage/saisons-ete-plage">plages ensoleillées de l\'été</a>, les <a href="/fr/coloriage/saisons-automne-feuilles">feuilles d\'automne</a> aux teintes dorées et orangées, les flocons de neige et les <a href="/fr/coloriage/saisons-hiver-bonhomme-neige">bonshommes de neige</a> de l\'hiver. Chaque saison est représentée par plusieurs scènes emblématiques qui permettent aux enfants d\'explorer les cycles de la nature.</p><h2>Apprendre le calendrier en coloriant</h2><p>Les coloriages saisons sont d\'excellents supports pédagogiques pour parler du temps qui passe, des changements climatiques, des habitudes des animaux selon les saisons (migration, hibernation) et des activités humaines liées à chaque période de l\'année. En automne, colorier les feuilles tombées et les châtaignes. En hiver, donner vie à des scènes enneigées avec le <a href="/fr/coloriage/saisons-hiver-ski">ski</a>. Au printemps, faire éclore les fleurs. En été, peindre des scènes de vacances. Ces coloriages rythment l\'année scolaire et accompagnent les enfants dans leur apprentissage du temps et du calendrier. Nos coloriages saisons sont disponibles gratuitement au format A4. Idéaux pour une utilisation en classe à chaque changement de saison ou pour des activités créatives en famille tout au long de l\'année.</p>',
    en: '<h2>Free printable seasons coloring pages</h2><p>The four seasons offer a parade of colors and atmospheres throughout the year. Our seasons coloring pages capture the magic of each period: <a href="/en/coloring/seasons-spring-flowers">spring flowers</a>, sunny <a href="/en/coloring/seasons-summer-beach">summer beaches</a>, <a href="/en/coloring/seasons-autumn-leaves">autumn leaves</a> in golden and orange hues, and <a href="/en/coloring/seasons-winter-snowman">snowmen</a> of winter. Each season is represented by several iconic scenes that let children explore nature\'s cycles.</p><h2>Learning the calendar through coloring</h2><p>Seasons coloring pages are excellent educational tools for discussing the passing of time, climate patterns, animal behaviors by season (migration, hibernation), and human activities tied to each time of year. In autumn, color fallen leaves and chestnuts. In winter, bring snowy scenes to life with <a href="/en/coloring/seasons-winter-skiing">skiing</a>. In spring, make flowers bloom. In summer, paint holiday scenes. These pages give rhythm to the school year and accompany children in learning about time and the calendar. Our seasons coloring pages are available for free in A4 format. Ideal for classroom use at each change of season or for creative family activities throughout the year.</p>',
  },
  'category.fetes.seoText': {
    fr: '<h2>Coloriages fêtes gratuits à imprimer</h2><p>Noël, Pâques, Halloween, les anniversaires : les fêtes sont des moments de joie collective que nos coloriages capturent avec éclat. Notre collection fêtes rassemble des dizaines de dessins à colorier pour célébrer toutes les occasions importantes de l\'année. Pour Noël, retrouvez le <a href="/fr/coloriage/fetes-noel-pere-noel">Père Noël</a> et son traîneau, les <a href="/fr/coloriage/fetes-noel-renne">rennes</a>, les étoiles et les <a href="/fr/coloriage/fetes-noel-sapin">sapins</a> décorés. Pour Pâques, colorisez des <a href="/fr/coloriage/fetes-paques-lapin">lapins</a> en chocolat, des <a href="/fr/coloriage/fetes-paques-oeuf">œufs</a> décorés et des petits poussins. Pour Halloween, donnez vie à des <a href="/fr/coloriage/fetes-halloween-citrouille">citrouilles</a> effrayantes, des fantômes rigolots et des sorcières en balai.</p><h2>Créer des traditions familiales</h2><p>Les coloriages de fête ont une place particulière dans le cœur des enfants car ils accompagnent les moments les plus heureux de leur vie. Colorier un Père Noël la veille de Noël ou décorer une citrouille avant Halloween crée des souvenirs et des traditions familiales durables. Ces activités créatives permettent aux enfants de s\'impliquer activement dans les préparatifs des fêtes et de contribuer à la magie des moments familiaux. Nos coloriages fêtes sont disponibles gratuitement au format A4. Téléchargez-les avant chaque occasion pour créer des activités créatives mémorables avec vos enfants.</p>',
    en: '<h2>Free printable holiday coloring pages</h2><p>Christmas, Easter, Halloween, birthdays — holidays are moments of collective joy that our coloring pages capture brilliantly. Our holiday collection brings together dozens of coloring illustrations to celebrate all the important occasions of the year. For Christmas, find <a href="/en/coloring/holidays-christmas-santa">Santa Claus</a> and his sleigh, <a href="/en/coloring/holidays-christmas-reindeer">reindeer</a>, stars, and decorated <a href="/en/coloring/holidays-christmas-tree">trees</a>. For Easter, color <a href="/en/coloring/holidays-easter-bunny">chocolate bunnies</a>, decorated <a href="/en/coloring/holidays-easter-egg">eggs</a>, and baby chicks. For Halloween, bring to life scary <a href="/en/coloring/holidays-halloween-pumpkin">pumpkins</a>, funny ghosts, and witches on broomsticks.</p><h2>Creating family traditions</h2><p>Holiday coloring pages hold a special place in children\'s hearts because they accompany the happiest moments of their lives. Coloring Santa Claus on Christmas Eve or decorating a pumpkin before Halloween creates lasting memories and family traditions. These creative activities allow children to actively participate in holiday preparations and contribute to the magic of family moments. Our holiday coloring pages are available for free in A4 format. Download them before each occasion to create memorable creative activities with your children.</p>',
  },
  'category.personnages.seoText': {
    fr: '<h2>Coloriages personnages gratuits à imprimer</h2><p>Les personnages de fiction captivent l\'imagination des enfants depuis toujours. Notre collection de coloriages personnages réunit des héros originaux : <a href="/fr/coloriage/personnages-pirate">pirates</a> intrépides, <a href="/fr/coloriage/personnages-ninja">ninjas</a> agiles, <a href="/fr/coloriage/personnages-viking">vikings</a> courageux, <a href="/fr/coloriage/personnages-magicien">magiciens</a> mystérieux. Chaque personnage a sa propre histoire et son propre univers visuel, invitant les enfants à créer et imaginer des aventures. Les dessins proposés couvrent une variété de styles graphiques : personnages ronds et mignons pour les plus petits, silhouettes plus détaillées pour les enfants plus grands.</p><h2>Stimuler la narration créative</h2><p>Certains personnages sont représentés seuls, d\'autres en scènes avec leurs amis, permettant aux enfants de colorier des histoires entières. La création de personnages est l\'une des activités créatives les plus enrichissantes pour les enfants. En choisissant les couleurs de la tenue d\'un <a href="/fr/coloriage/personnages-roi">roi</a> ou d\'une <a href="/fr/coloriage/personnages-reine">reine</a>, l\'enfant s\'approprie le personnage et lui invente une identité. C\'est le début de la narration créative et de l\'écriture imaginative. Ces coloriages s\'accompagnent naturellement d\'activités de conte et d\'écriture : quel est le nom de ce personnage ? Où habite-t-il ? Quelle est son aventure ? Nos coloriages personnages sont disponibles gratuitement au format A4, idéaux pour stimuler l\'imagination des enfants.</p>',
    en: '<h2>Free printable character coloring pages</h2><p>Fictional characters have always captivated children\'s imaginations. Our character coloring pages bring together original heroes: daring <a href="/en/coloring/characters-pirate">pirates</a>, agile <a href="/en/coloring/characters-ninja">ninjas</a>, courageous <a href="/en/coloring/characters-viking">vikings</a>, mysterious <a href="/en/coloring/characters-wizard">wizards</a>. Each character has their own story and visual world, inviting children to create and imagine adventures. The illustrations cover a variety of graphic styles: round and cute characters for younger children, more detailed silhouettes for older ones.</p><h2>Sparking creative storytelling</h2><p>Some characters appear alone, others in scenes with friends, allowing children to color entire stories. Character creation is one of the most enriching creative activities for children. By choosing the colors for a <a href="/en/coloring/characters-king">king</a>\'s robe or a <a href="/en/coloring/characters-queen">queen</a>\'s crown, children claim the character and invent their identity. This is the beginning of creative storytelling and imaginative writing. These coloring pages naturally accompany storytelling and writing activities: what is this character\'s name? Where do they live? What is their adventure? Our character coloring pages are available for free in A4 format, perfect for sparking children\'s imagination.</p>',
  },
  'category.contes.seoText': {
    fr: '<h2>Coloriages contes de fées gratuits à imprimer</h2><p>Il était une fois... une collection de coloriages dédiée aux contes et aux histoires qui bercent l\'enfance depuis des générations. Le <a href="/fr/coloriage/contes-chaperon-rouge">Petit Chaperon Rouge</a>, <a href="/fr/coloriage/contes-geant-haricot">Jack et le Haricot Magique</a>, la <a href="/fr/coloriage/contes-rose-enchantee">Rose enchantée</a> : les héros des grands contes classiques prennent vie dans nos illustrations à colorier. Nos dessins représentent les scènes les plus emblématiques de ces histoires intemporelles. Les enfants qui connaissent ces histoires prennent un plaisir particulier à colorier les personnages qu\'ils imaginaient depuis leurs premières lectures.</p><h2>Accompagner la lecture avec le coloriage</h2><p>Les coloriages contes sont d\'excellents supports pour accompagner la lecture à voix haute. Découvrez aussi notre <a href="/fr/coloriage/contes-licorne-arc-en-ciel">licorne arc-en-ciel</a> et la <a href="/fr/coloriage/contes-fee-foret">fée de la forêt</a>. Après avoir lu ou raconté l\'histoire, proposez aux enfants de colorier leurs personnages préférés : c\'est une façon de prolonger le plaisir de la lecture et de vérifier leur compréhension de l\'histoire. Ces coloriages renforcent l\'amour de la littérature et sensibilisent les enfants à la richesse du patrimoine culturel. Nos coloriages contes sont disponibles gratuitement au format A4. Parfaits pour les coins lecture, les bibliothèques scolaires ou les activités de lecture en famille.</p>',
    en: '<h2>Free printable fairy tale coloring pages</h2><p>Once upon a time... a coloring collection dedicated to fairy tales and stories that have shaped childhood for generations. <a href="/en/coloring/tales-little-red-hood">Little Red Riding Hood</a>, <a href="/en/coloring/tales-beanstalk-giant">Jack and the Beanstalk</a>, the <a href="/en/coloring/tales-enchanted-rose">Enchanted Rose</a> — the heroes of great classic fairy tales come to life in our coloring illustrations. Our drawings depict the most iconic scenes from these timeless stories. Children who know these stories take particular delight in coloring the characters they have imagined since their first readings.</p><h2>Supporting reading with coloring</h2><p>Fairy tale coloring pages are excellent supports for read-aloud activities. Also discover our <a href="/en/coloring/tales-rainbow-unicorn">rainbow unicorn</a> and the <a href="/en/coloring/tales-forest-fairy">forest fairy</a>. After reading or telling the story, invite children to color their favorite characters — it\'s a way to extend the pleasure of reading and check their understanding. These coloring pages strengthen love of literature and introduce children to the richness of cultural heritage. Our fairy tale coloring pages are available for free in A4 format. Perfect for reading corners, school libraries, or family reading activities.</p>',
  },
  'category.drole.seoText': {
    fr: '<h2>Coloriages drôles gratuits à imprimer</h2><p>Rires, grimaces et situations absurdes garantis ! Nos coloriages drôles sont conçus pour faire sourire les enfants tout en les invitant à colorier des personnages hilarants dans des situations comiques. Un <a href="/fr/coloriage/drole-chat-astronaute">chat astronaute</a>, un <a href="/fr/coloriage/drole-dinosaure-skateboard">dinosaure en skateboard</a>, un <a href="/fr/coloriage/drole-pingouin-chef">pingouin chef cuisinier</a> : notre collection humoristique est un concentré de bonne humeur. Le dessin humoristique a ses propres codes graphiques : les expressions faciales exagérées, les yeux en spirale, les personnages qui tombent, les éclairs de colère stylisés.</p><h2>L\'humour, clé du développement</h2><p>En coloriant ces dessins, les enfants apprennent à lire les émotions dans les visages et à comprendre les mécanismes du comique visuel. L\'humour est une dimension importante du développement de l\'enfant. Comprendre pourquoi quelque chose est drôle, apprécier l\'absurde, créer ses propres blagues : ce sont des étapes importantes du développement cognitif et social. Découvrez aussi la <a href="/fr/coloriage/drole-grenouille-chevalier">grenouille chevalier</a> et le <a href="/fr/coloriage/drole-singe-voiture">singe en voiture</a>. Ces coloriages sont parfaits pour égayer une journée maussade, décorer la chambre d\'un enfant ou créer des cartes de vœux originales et rigolotes. Nos coloriages drôles sont disponibles gratuitement au format A4. Imprimez-les pour des fous rires garantis et des souvenirs créatifs inoubliables.</p>',
    en: '<h2>Free printable funny coloring pages</h2><p>Laughter, silly faces, and absurd situations guaranteed! Our funny coloring pages are designed to make children smile while inviting them to color hilarious characters in comic situations. A <a href="/en/coloring/funny-cat-astronaut">cat astronaut</a>, a <a href="/en/coloring/funny-dinosaur-skateboard">skateboarding dinosaur</a>, a <a href="/en/coloring/funny-penguin-chef">penguin chef</a> — our humor collection is a concentration of good cheer. Comic drawing has its own visual codes: exaggerated facial expressions, spiral eyes, falling characters, stylized anger lightning bolts.</p><h2>Humor as a development key</h2><p>By coloring these drawings, children learn to read emotions in faces and understand the mechanisms of visual comedy. Humor is an important dimension of a child\'s development. Understanding why something is funny, appreciating the absurd, creating their own jokes — these are important steps in cognitive and social development. Also discover the <a href="/en/coloring/funny-frog-knight">frog knight</a> and the <a href="/en/coloring/funny-monkey-car">monkey in a car</a>. These pages are perfect for brightening a gloomy day, decorating a child\'s room, or creating original and amusing greeting cards. Our funny coloring pages are available for free in A4 format. Print them for guaranteed laughter and unforgettable creative memories.</p>',
  },
  'category.musique.seoText': {
    fr: '<h2>Coloriages musique gratuits à imprimer</h2><p>La musique inspire les enfants et stimule leur créativité ! Notre collection de coloriages musique propose des instruments variés à colorier : <a href="/fr/coloriage/musique-guitare">guitare</a>, <a href="/fr/coloriage/musique-piano">piano</a>, <a href="/fr/coloriage/musique-batterie">batterie</a>, <a href="/fr/coloriage/musique-violon">violon</a>, <a href="/fr/coloriage/musique-trompette">trompette</a> et bien d\'autres. Chaque instrument est représenté dans un style accessible et ludique, permettant aux enfants de découvrir la diversité des instruments de musique tout en s\'amusant.</p><h2>Découvrir les instruments en coloriant</h2><p>Le coloriage musical est une excellente activité complémentaire à l\'éveil musical. En coloriant un <a href="/fr/coloriage/musique-saxophone">saxophone</a> ou une <a href="/fr/coloriage/musique-harpe">harpe</a>, l\'enfant s\'approprie visuellement l\'instrument et retient plus facilement son nom et sa forme. Ces coloriages accompagnent parfaitement les cours de musique et les activités d\'écoute. Nos coloriages musique sont disponibles gratuitement au format A4, idéaux pour les professeurs de musique, les parents mélomanes et tous les petits artistes en herbe.</p>',
    en: '<h2>Free printable music coloring pages</h2><p>Music inspires children and stimulates their creativity! Our music coloring page collection features a variety of instruments to color: <a href="/en/coloring/music-guitar">guitar</a>, <a href="/en/coloring/music-piano">piano</a>, <a href="/en/coloring/music-drums">drums</a>, <a href="/en/coloring/music-violin">violin</a>, <a href="/en/coloring/music-trumpet">trumpet</a>, and many more. Each instrument is illustrated in an accessible and playful style, allowing children to discover the diversity of musical instruments while having fun.</p><h2>Discover instruments through coloring</h2><p>Musical coloring is an excellent complementary activity to music education. By coloring a <a href="/en/coloring/music-saxophone">saxophone</a> or a <a href="/en/coloring/music-harp">harp</a>, children visually connect with the instrument and more easily remember its name and shape. These coloring pages perfectly complement music lessons and listening activities. Our music coloring pages are available for free in A4 format, ideal for music teachers, music-loving parents, and all budding young artists.</p>',
  },
  'category.nourriture.seoText': {
    fr: '<h2>Coloriages nourriture gratuits à imprimer</h2><p>Gâteaux, fruits, pizzas et glaces : nos coloriages nourriture mettent l\'eau à la bouche ! Cette collection gourmande propose des aliments et des plats appétissants à colorier : une <a href="/fr/coloriage/nourriture-pizza">pizza</a> garnie, une <a href="/fr/coloriage/nourriture-glace">glace</a> fondante, un <a href="/fr/coloriage/nourriture-gateau">gâteau d\'anniversaire</a> décoré, des <a href="/fr/coloriage/nourriture-fruits">fruits</a> colorés et une <a href="/fr/coloriage/nourriture-boulangerie">boulangerie</a> pleine de pains et viennoiseries.</p><h2>Apprendre l\'alimentation en s\'amusant</h2><p>Les coloriages nourriture sont une façon ludique de parler alimentation avec les enfants. En coloriant des fruits et des légumes, on peut aborder les groupes alimentaires, les couleurs des aliments et l\'importance d\'une alimentation variée. Ces dessins sont aussi parfaits pour décorer une cuisine ou accompagner des ateliers culinaires pour enfants. Nos coloriages nourriture sont disponibles gratuitement au format A4. Imprimez-les pour des activités créatives qui donnent faim !</p>',
    en: '<h2>Free printable food coloring pages</h2><p>Cakes, fruits, pizzas, and ice cream — our food coloring pages are mouth-watering! This delicious collection features appetizing foods and dishes to color: a loaded <a href="/en/coloring/food-pizza">pizza</a>, a melting <a href="/en/coloring/food-ice-cream-sundae">ice cream sundae</a>, a decorated <a href="/en/coloring/food-birthday-cake">birthday cake</a>, colorful <a href="/en/coloring/food-fruit-bowl">fruits</a>, and a <a href="/en/coloring/food-french-bakery">French bakery</a> full of breads and pastries.</p><h2>Learning about food through fun</h2><p>Food coloring pages are a playful way to talk about nutrition with children. By coloring fruits and vegetables, you can discuss food groups, the colors of foods, and the importance of a varied diet. These drawings are also perfect for decorating a kitchen or accompanying children\'s cooking workshops. Our food coloring pages are available for free in A4 format. Print them for creative activities that will make you hungry!</p>',
  },
  'category.pirates.seoText': {
    fr: '<h2>Coloriages pirates gratuits à imprimer</h2><p>À l\'abordage ! Notre collection de coloriages pirates transporte les enfants dans un monde d\'aventures maritimes. Découvrez des <a href="/fr/coloriage/pirates-navire">navires</a> majestueux, des <a href="/fr/coloriage/pirates-ile">îles</a> mystérieuses, des <a href="/fr/coloriage/pirates-tresor">trésors</a> enfouis, des <a href="/fr/coloriage/pirates-carte">cartes au trésor</a> et des <a href="/fr/coloriage/pirates-perroquet">perroquets</a> fidèles compagnons. Chaque dessin est une invitation à l\'aventure et à l\'imagination.</p><h2>Naviguer et imaginer</h2><p>Les pirates fascinent les enfants depuis des générations. En coloriant ces personnages audacieux et leurs univers, les enfants développent leur imagination narrative et s\'inventent des histoires de haute mer. Les coloriages pirates sont parfaits pour les fêtes d\'anniversaire à thème, les activités de vacances ou simplement pour s\'évader dans un monde d\'aventure. Nos coloriages pirates sont disponibles gratuitement au format A4, prêts à imprimer pour de grandes aventures créatives.</p>',
    en: '<h2>Free printable pirate coloring pages</h2><p>Ahoy, mateys! Our pirate coloring page collection transports children into a world of maritime adventures. Discover majestic <a href="/en/coloring/pirates-ship">ships</a>, mysterious <a href="/en/coloring/pirates-island">islands</a>, buried <a href="/en/coloring/pirates-treasure">treasures</a>, <a href="/en/coloring/pirates-map">treasure maps</a>, and faithful <a href="/en/coloring/pirates-parrot">parrot</a> companions. Each drawing is an invitation to adventure and imagination.</p><h2>Navigate and imagine</h2><p>Pirates have fascinated children for generations. By coloring these bold characters and their worlds, children develop their narrative imagination and invent stories of the high seas. Pirate coloring pages are perfect for themed birthday parties, vacation activities, or simply escaping into a world of adventure. Our pirate coloring pages are available for free in A4 format, ready to print for great creative adventures.</p>',
  },
  'category.robots.seoText': {
    fr: '<h2>Coloriages robots gratuits à imprimer</h2><p>Bienvenue dans le futur ! Nos coloriages robots proposent des machines amicales et créatives à colorier. Découvrez un <a href="/fr/coloriage/robots-pompier">robot pompier</a>, un <a href="/fr/coloriage/robots-danseur">robot danseur</a>, un <a href="/fr/coloriage/robots-jardinier">robot jardinier</a>, un <a href="/fr/coloriage/robots-chef">robot chef cuisinier</a> et un <a href="/fr/coloriage/robots-astronaute">robot astronaute</a>. Chaque robot a sa propre personnalité et son propre métier, montrant que la technologie peut être amusante et créative.</p><h2>Technologie et créativité</h2><p>Les coloriages robots stimulent l\'imagination des enfants pour la science et la technologie. En coloriant ces personnages mécaniques attachants, les enfants explorent des concepts de robotique et d\'intelligence artificielle de manière ludique. Ces dessins sont parfaits pour les passionnés de science-fiction, les ateliers STEM et tous les petits inventeurs. Nos coloriages robots sont disponibles gratuitement au format A4, prêts à imprimer pour des aventures technologiques colorées.</p>',
    en: '<h2>Free printable robot coloring pages</h2><p>Welcome to the future! Our robot coloring pages feature friendly and creative machines to color. Discover a <a href="/en/coloring/robots-firefighter">firefighter robot</a>, a <a href="/en/coloring/robots-dancer">dancing robot</a>, a <a href="/en/coloring/robots-gardener">gardener robot</a>, a <a href="/en/coloring/robots-chef">chef robot</a>, and an <a href="/en/coloring/robots-astronaut">astronaut robot</a>. Each robot has its own personality and profession, showing that technology can be fun and creative.</p><h2>Technology and creativity</h2><p>Robot coloring pages stimulate children\'s imagination for science and technology. By coloring these endearing mechanical characters, children explore concepts of robotics and artificial intelligence in a playful way. These drawings are perfect for science fiction fans, STEM workshops, and all young inventors. Our robot coloring pages are available for free in A4 format, ready to print for colorful technological adventures.</p>',
  },
  'category.mandalas.seoText': {
    fr: '<h2>Coloriages mandalas gratuits pour adultes</h2><p>Les mandalas sont bien plus que de simples dessins à colorier : ce sont des œuvres d\'art géométriques aux vertus méditatives reconnues. Issu des traditions hindoue et bouddhiste, le mandala représente l\'univers et l\'équilibre. Nos coloriages mandalas pour adultes proposent une large gamme de motifs : <a href="/fr/coloriage/mandalas-floral">mandala floral</a>, <a href="/fr/coloriage/mandalas-geometrique">géométrique</a>, <a href="/fr/coloriage/mandalas-lotus">lotus</a>, <a href="/fr/coloriage/mandalas-celtique">celtique</a> et <a href="/fr/coloriage/mandalas-tribal">tribal</a>. La répétition de motifs en cercles concentriques crée un effet hypnotique propice à la concentration et à la relaxation.</p><h2>Le mandala comme outil anti-stress</h2><p>Colorier un mandala permet de se déconnecter du stress quotidien, de ralentir le rythme et de se concentrer sur le moment présent — une forme de méditation active accessible à tous. De nombreux thérapeutes recommandent le coloriage de mandalas comme outil anti-stress. Contrairement à d\'autres formes d\'art qui requièrent un apprentissage technique, les mandalas sont accessibles à tous : aucune compétence artistique n\'est nécessaire pour commencer. Nos mandalas adultes couvrent un large spectre de complexité : des motifs floraux simples pour les débutants aux entrelacs géométriques complexes pour les experts. Choisissez vos crayons, feutres ou aquarelles, et laissez-vous porter par le flux créatif. Nos coloriages mandalas sont disponibles gratuitement au format A4 haute résolution, prêts à imprimer pour votre prochain moment de détente.</p>',
    en: '<h2>Free mandala coloring pages for adults</h2><p>Mandalas are much more than simple coloring pages: they are geometric artworks with recognized meditative virtues. Originating from Hindu and Buddhist traditions, the mandala represents the universe and balance. Our adult mandala coloring pages offer a wide range of patterns: <a href="/en/coloring/mandalas-floral">floral mandala</a>, <a href="/en/coloring/mandalas-geometric">geometric</a>, <a href="/en/coloring/mandalas-lotus">lotus</a>, <a href="/en/coloring/mandalas-celtic">Celtic</a>, and <a href="/en/coloring/mandalas-tribal">tribal</a>. The repetition of motifs in concentric circles creates a hypnotic effect conducive to concentration and relaxation.</p><h2>Mandalas as an anti-stress tool</h2><p>Coloring a mandala allows you to disconnect from daily stress, slow down, and focus on the present moment — a form of active meditation accessible to everyone. Many therapists recommend mandala coloring as an anti-stress tool. Unlike other art forms that require technical training, mandalas are accessible to all: no artistic skill is needed to begin. Our adult mandalas span a wide complexity spectrum: simple floral patterns for beginners to intricate geometric weaves for experts. Choose your colored pencils, markers, or watercolors, and let yourself be carried by the creative flow. Our mandala coloring pages are available for free in A4 high-resolution format, ready to print for your next relaxation session.</p>',
  },
  'category.mosaiques.seoText': {
    fr: '<h2>Coloriages mosaïques gratuits pour adultes</h2><p>Les mosaïques sont l\'un des arts les plus anciens de l\'humanité, de l\'Antiquité <a href="/fr/coloriage/mosaiques-romaine">romaine</a> aux <a href="/fr/coloriage/mosaiques-azulejo">azulejos</a> portugais en passant par les <a href="/fr/coloriage/mosaiques-marocaine">zellige marocains</a>. Nos coloriages mosaïques pour adultes s\'inspirent de ces traditions artistiques millénaires pour proposer des motifs géométriques à colorier, case par case, comme un vrai artisan mosaïste. Chaque coloriage mosaïque est composé de petites cellules — carrées, <a href="/fr/coloriage/mosaiques-hexagonale">hexagonales</a>, triangulaires ou irrégulières — que vous remplissez de couleurs selon votre inspiration.</p><h2>Explorer la théorie des couleurs</h2><p>Le résultat final est une œuvre d\'art nuancée et harmonieuse, dont l\'effet d\'ensemble ne se révèle qu\'une fois toutes les cases colorées. Cette approche analytique du coloriage est particulièrement satisfaisante et méditative. Découvrez aussi nos mosaïques <a href="/fr/coloriage/mosaiques-vitrail">vitrail</a> et <a href="/fr/coloriage/mosaiques-art-nouveau">Art Nouveau</a>. Elle nécessite de la patience et de la précision, mais chaque petite zone colorée représente un micro-accomplissement qui nourrit la satisfaction créative. Les mosaïques permettent aussi d\'explorer la théorie des couleurs : l\'harmonie des teintes voisines, les contrastes entre couleurs complémentaires, les effets de dégradé. Nos coloriages mosaïques sont disponibles gratuitement au format A4 haute résolution. Utilisez des feutres fins pour les petites cases et des crayons de couleur pour les plus grandes surfaces.</p>',
    en: '<h2>Free mosaic coloring pages for adults</h2><p>Mosaics are one of humanity\'s oldest art forms, from <a href="/en/coloring/mosaics-roman">Roman</a> antiquity to Portuguese <a href="/en/coloring/mosaics-azulejo">azulejos</a> and <a href="/en/coloring/mosaics-moroccan">Moroccan zellige</a>. Our adult mosaic coloring pages draw inspiration from these millennia-old artistic traditions to offer geometric patterns to color cell by cell, like a true mosaic craftsman. Each mosaic coloring page is composed of small cells — square, <a href="/en/coloring/mosaics-hexagonal">hexagonal</a>, triangular, or irregular — that you fill with colors according to your inspiration.</p><h2>Exploring color theory</h2><p>The final result is a nuanced and harmonious artwork, whose overall effect only reveals itself once all cells are colored. This analytical approach to coloring is particularly satisfying and meditative. Also discover our <a href="/en/coloring/mosaics-stained-glass">stained glass</a> and <a href="/en/coloring/mosaics-art-nouveau">Art Nouveau</a> mosaics. It requires patience and precision, but each small colored area represents a micro-achievement that feeds creative satisfaction. Mosaics also allow you to explore color theory: the harmony of neighboring hues, contrasts between complementary colors, gradient effects. Our mosaic coloring pages are available for free in A4 high-resolution format. Use fine-tipped markers for small cells and colored pencils for larger areas.</p>',
  },
  'category.abstrait.seoText': {
    fr: '<h2>Coloriages abstraits gratuits pour adultes</h2><p>L\'art abstrait libère l\'imagination de toute contrainte réaliste. Dans nos coloriages abstraits pour adultes, il n\'y a pas de représentation d\'objets ou de personnages reconnaissables : seulement des formes, des lignes, des courbes et des espaces à remplir selon votre propre vision. Explorez nos motifs <a href="/fr/coloriage/abstrait-geometrique">géométriques</a>, les <a href="/fr/coloriage/abstrait-spirales">spirales</a> hypnotiques, les <a href="/fr/coloriage/abstrait-fractale">fractales</a> complexes ou l\'<a href="/fr/coloriage/abstrait-op-art">Op Art</a> vibrant. Chaque coloriage abstrait est une invitation à l\'exploration créative sans règles ni contraintes.</p><h2>La liberté totale du coloriage abstrait</h2><p>Vous pouvez choisir une palette monochrome pour un effet épuré et contemporain, ou opter pour des couleurs vives et contrastées pour un résultat éclatant et dynamique. Le résultat sera unique, reflet de votre sensibilité artistique du moment. L\'art abstrait est libérateur car il n\'y a pas de mauvaise façon de le colorier. Découvrez aussi notre <a href="/fr/coloriage/abstrait-zentangle">zentangle</a> et nos <a href="/fr/coloriage/abstrait-ondulations">ondulations</a>. Contrairement aux coloriages figuratifs où vous pouvez vous demander « le ciel doit-il être bleu ? », l\'abstrait répond : colorez comme vous le sentez. Les coloriages abstraits sont aussi d\'excellents objets décoratifs une fois terminés : encadrés, ils forment de beaux tableaux originaux pour décorer votre intérieur. Nos coloriages abstraits sont disponibles gratuitement au format A4. Imprimez-les sur du beau papier pour un rendu optimal et accrochez vos créations avec fierté.</p>',
    en: '<h2>Free abstract coloring pages for adults</h2><p>Abstract art frees the imagination from all realistic constraints. In our adult abstract coloring pages, there are no recognizable objects or characters — only shapes, lines, curves, and spaces to fill according to your own vision. Explore our <a href="/en/coloring/abstract-geometric">geometric</a> patterns, hypnotic <a href="/en/coloring/abstract-spirals">spirals</a>, complex <a href="/en/coloring/abstract-fractal">fractals</a>, or vibrant <a href="/en/coloring/abstract-op-art">Op Art</a>. Each abstract coloring page is an invitation to creative exploration with no rules or constraints.</p><h2>Total freedom in abstract coloring</h2><p>You can choose a monochrome palette for a clean, contemporary effect, or opt for bright, contrasting colors for a vibrant and dynamic result. The outcome will be unique, reflecting your current artistic sensibility. Abstract art is liberating because there is no wrong way to color it. Also discover our <a href="/en/coloring/abstract-zentangle">zentangle</a> and <a href="/en/coloring/abstract-waves">wave</a> patterns. Unlike figurative coloring pages where you might wonder \'should the sky be blue?\', abstract art answers: color as you feel. Finished abstract coloring pages also make excellent decorative objects: framed, they create beautiful original artworks to decorate your home. Our abstract coloring pages are available for free in A4 format. Print them on quality paper for the best result and display your creations with pride.</p>',
  },
  'category.cartes.seoText': {
    fr: '<h2>Coloriages cartes géographiques gratuits</h2><p>Explorez le monde depuis votre table grâce à nos coloriages cartes géographiques ! Notre collection propose des cartes illustrées du <a href="/fr/coloriage/cartes-monde">monde</a>, de l\'<a href="/fr/coloriage/cartes-europe">Europe</a>, de la <a href="/fr/coloriage/cartes-france">France</a>, de l\'<a href="/fr/coloriage/cartes-afrique">Afrique</a> et du <a href="/fr/coloriage/cartes-japon">Japon</a> que les adultes et les enfants peuvent colorier pour apprendre la géographie de manière ludique et créative. Colorier une carte du monde est une expérience à la fois artistique et éducative. En donnant une couleur différente à chaque pays ou région, vous mémorisez naturellement leur emplacement et leurs frontières.</p><h2>Apprendre la géographie en coloriant</h2><p>C\'est une méthode d\'apprentissage par le faire, bien plus efficace que la simple lecture d\'un atlas. Nos cartes illustrées intègrent des éléments décoratifs : boussoles, roses des vents et parfois des petites illustrations des productions typiques de chaque région. Ne manquez pas notre <a href="/fr/coloriage/cartes-tresor">carte au trésor</a> pour les aventuriers ! Ces détails rendent le coloriage de cartes particulièrement enrichissant et esthétiquement plaisant. Une carte du monde coloriée avec soin fait un magnifique poster éducatif pour la chambre d\'un enfant ou un bureau d\'adulte. Nos coloriages cartes sont disponibles gratuitement au format A4. Pour les cartes de grand format, assemblez plusieurs feuilles pour un rendu encore plus impressionnant et éducatif.</p>',
    en: '<h2>Free geographical map coloring pages</h2><p>Explore the world from your table with our geographical map coloring pages! Our collection features illustrated maps of the <a href="/en/coloring/maps-world">world</a>, <a href="/en/coloring/maps-europe">Europe</a>, <a href="/en/coloring/maps-france">France</a>, <a href="/en/coloring/maps-africa">Africa</a>, and <a href="/en/coloring/maps-japan">Japan</a> that adults and children can color to learn geography in a fun and creative way. Coloring a world map is both an artistic and educational experience. By giving different colors to each country or region, you naturally memorize their locations and borders.</p><h2>Learning geography through coloring</h2><p>It\'s a learn-by-doing method, far more effective than simply reading an atlas. Our illustrated maps incorporate decorative elements: compasses, wind roses, and sometimes small illustrations of typical productions from each region. Don\'t miss our <a href="/en/coloring/maps-treasure">treasure map</a> for adventurers! These details make map coloring particularly enriching and aesthetically pleasing. A carefully colored world map makes a beautiful educational poster for a child\'s room or an adult\'s office. Our map coloring pages are available for free in A4 format. For large-format maps, assemble several sheets for an even more impressive and educational result.</p>',
  },
  'category.paysages.seoText': {
    fr: '<h2>Coloriages paysages gratuits pour adultes</h2><p>La montagne enneigée, la forêt mystérieuse, la plage au coucher du soleil, la campagne verdoyante : les paysages offrent une infinité de sources d\'inspiration pour les artistes. Nos coloriages paysages pour adultes proposent des vues panoramiques : les <a href="/fr/coloriage/paysages-alpes">Alpes</a> majestueuses, le <a href="/fr/coloriage/paysages-canyon">canyon</a> impressionnant, la <a href="/fr/coloriage/paysages-cote-bretonne">côte bretonne</a> sauvage, les champs de <a href="/fr/coloriage/paysages-lavande">lavande</a> provençaux. Chaque paysage est soigneusement composé pour offrir un équilibre visuel satisfaisant : un premier plan détaillé, un milieu habité et un arrière-plan atmosphérique.</p><h2>Lumière, couleur et perspective</h2><p>Cette structure classique de la composition paysagère permet d\'explorer les techniques de perspective et de rendu de la profondeur. Colorier un paysage invite à réfléchir à la lumière et à l\'atmosphère : un paysage de matin aura des teintes froides et brumeuses, un coucher de soleil des orangés et des roses flamboyants. Découvrez aussi notre <a href="/fr/coloriage/paysages-foret-tropicale">forêt tropicale</a> et la <a href="/fr/coloriage/paysages-mer-voiliers">mer aux voiliers</a>. Ces réflexions sur la couleur et la lumière développent la sensibilité artistique et la conscience visuelle. Les paysages terminés font de beaux décors pour la maison ou le bureau, rappelant des lieux aimés ou évoquant des voyages rêvés. Nos coloriages paysages sont disponibles gratuitement au format A4 haute résolution. Utilisez des aquarelles ou des crayons de couleur pour les effets de dégradé et les textures atmosphériques.</p>',
    en: '<h2>Free landscape coloring pages for adults</h2><p>Snow-capped mountains, mysterious forests, beaches at sunset, verdant countryside — landscapes offer an infinite source of inspiration for artists. Our adult landscape coloring pages feature panoramic views: the majestic <a href="/en/coloring/landscapes-alps">Alps</a>, an impressive <a href="/en/coloring/landscapes-canyon">canyon</a>, the wild <a href="/en/coloring/landscapes-breton-coast">Breton coast</a>, and <a href="/en/coloring/landscapes-lavender">lavender</a> fields of Provence. Each landscape is carefully composed to offer satisfying visual balance: a detailed foreground, a middle ground with life, and an atmospheric background.</p><h2>Light, color, and perspective</h2><p>This classic landscape composition structure allows exploration of perspective techniques and depth rendering. Coloring a landscape invites reflection on light and atmosphere: a morning landscape has cool, misty tones; a sunset blazes with oranges and pinks. Also discover our <a href="/en/coloring/landscapes-tropical-forest">tropical forest</a> and <a href="/en/coloring/landscapes-sailboats-sea">sailboats at sea</a>. These reflections on color and light develop artistic sensibility and visual awareness. Finished landscapes make beautiful decorations for the home or office, recalling beloved places or evoking dreamed-of travels. Our landscape coloring pages are available for free in A4 high-resolution format. Use watercolors or colored pencils for gradient effects and atmospheric textures.</p>',
  },
};

export function t(key: string, locale: Locale): string {
  return translations[key]?.[locale] ?? key;
}

export function ti(key: string, locale: Locale, params: Record<string, string>): string {
  let result = t(key, locale);
  for (const [k, v] of Object.entries(params)) {
    result = result.replace(`{${k}}`, v);
  }
  return result;
}

export function getCategoryLabel(category: Category, locale: Locale): string {
  return t(`category.${category}`, locale);
}

export function getLocalePath(locale: Locale, path: string = ''): string {
  return `/${locale}${path}`;
}

const enSlugs: Record<Category, string> = {
  animaux: 'animals',
  'animaux-marins': 'sea-animals',
  ferme: 'farm',
  vehicules: 'vehicles',
  nature: 'nature',
  alphabet: 'alphabet',
  dinosaures: 'dinosaurs',
  'super-heros': 'superheroes',
  espace: 'space',
  'princesses-chevaliers': 'princesses-knights',
  metiers: 'jobs',
  sport: 'sport',
  saisons: 'seasons',
  fetes: 'holidays',
  mandalas: 'mandalas',
  mosaiques: 'mosaics',
  abstrait: 'abstract',
  cartes: 'maps',
  personnages: 'characters',
  contes: 'fairy-tales',
  drole: 'funny',
  musique: 'music',
  nourriture: 'food',
  pirates: 'pirates',
  robots: 'robots',
  paysages: 'landscapes',
};

export function getCategorySlug(category: Category, locale: Locale): string {
  if (locale === 'en') {
    return enSlugs[category];
  }
  return category;
}

export function getColoringBasePath(locale: Locale): string {
  return locale === 'fr' ? 'coloriage' : 'coloring';
}

export function getPrivacyPath(locale: Locale): string {
  return getLocalePath(locale, locale === 'fr' ? '/confidentialite' : '/privacy');
}

export function getTermsPath(locale: Locale): string {
  return getLocalePath(locale, locale === 'fr' ? '/conditions' : '/terms');
}

export function getCategoriesPath(locale: Locale): string {
  return getLocalePath(locale, locale === 'fr' ? '/categories' : '/categories');
}
