export type Locale = 'fr' | 'en';

export const defaultLocale: Locale = 'fr';
export const locales: Locale[] = ['fr', 'en'];

export const kidsCategories = [
  'animaux',
  'vehicules',
  'nature',
  'alphabet',
  'dinosaures',
  'super-heros',
  'espace',
  'princesses-chevaliers',
  'metiers',
  'sport',
  'saisons',
  'fetes',
  'personnages',
  'contes',
  'drole',
] as const;

export const adultCategories = [
  'mandalas',
  'mosaiques',
  'abstrait',
  'cartes',
  'paysages',
] as const;

export const categories = [...kidsCategories, ...adultCategories] as const;

export type Category = (typeof categories)[number];

const translations: Record<string, Record<Locale, string>> = {
  'site.title': {
    fr: 'Colotopia — Coloriages Gratuits à Imprimer',
    en: 'Colotopia — Free Printable Coloring Pages',
  },
  'site.description': {
    fr: 'Colotopia : des centaines de coloriages gratuits à imprimer pour les enfants et les adultes. Animaux, véhicules, mandalas, mosaïques et plus encore !',
    en: 'Colotopia: hundreds of free printable coloring pages for kids and adults. Animals, vehicles, mandalas, mosaics and more!',
  },
  'nav.home': { fr: 'Accueil', en: 'Home' },
  'nav.categories': { fr: 'Catégories', en: 'Categories' },
  'audience.enfants': { fr: 'Enfants', en: 'Kids' },
  'audience.adultes': { fr: 'Adultes', en: 'Adults' },
  'category.animaux': { fr: 'Animaux', en: 'Animals' },
  'category.vehicules': { fr: 'Véhicules', en: 'Vehicles' },
  'category.nature': { fr: 'Nature', en: 'Nature' },
  'category.alphabet': { fr: 'Alphabet', en: 'Alphabet' },
  'category.dinosaures': { fr: 'Dinosaures', en: 'Dinosaurs' },
  'category.super-heros': { fr: 'Super-héros', en: 'Superheroes' },
  'category.espace': { fr: 'Espace', en: 'Space' },
  'category.princesses-chevaliers': { fr: 'Princesses & Chevaliers', en: 'Princesses & Knights' },
  'category.metiers': { fr: 'Métiers', en: 'Jobs' },
  'category.sport': { fr: 'Sport', en: 'Sport' },
  'category.saisons': { fr: 'Saisons', en: 'Seasons' },
  'category.fetes': { fr: 'Fêtes', en: 'Holidays' },
  'category.mandalas': { fr: 'Mandalas', en: 'Mandalas' },
  'category.mosaiques': { fr: 'Mosaïques', en: 'Mosaics' },
  'category.abstrait': { fr: 'Abstrait', en: 'Abstract' },
  'category.cartes': { fr: 'Cartes', en: 'Maps' },
  'category.personnages': { fr: 'Personnages', en: 'Characters' },
  'category.contes': { fr: 'Contes', en: 'Fairy Tales' },
  'category.drole': { fr: 'Drôle', en: 'Funny' },
  'category.paysages': { fr: 'Paysages', en: 'Landscapes' },
  'coloring.download': { fr: 'Télécharger le PDF', en: 'Download PDF' },
  'coloring.print': { fr: 'Imprimer', en: 'Print' },
  'footer.rights': {
    fr: 'Tous droits réservés',
    en: 'All rights reserved',
  },
  'footer.kids': { fr: 'Coloriages Enfants', en: 'Kids Coloring' },
  'footer.adults': { fr: 'Coloriages Adultes', en: 'Adult Coloring' },
  'footer.legal': { fr: 'Informations', en: 'Information' },
  'footer.privacy': { fr: 'Politique de confidentialité', en: 'Privacy Policy' },
  'footer.terms': { fr: "Conditions d'utilisation", en: 'Terms of Use' },
  'footer.contact': { fr: 'Contact', en: 'Contact' },
  'share.label': { fr: 'Partager', en: 'Share' },
  'share.whatsapp': { fr: 'Partager sur WhatsApp', en: 'Share on WhatsApp' },
  'share.facebook': { fr: 'Partager sur Facebook', en: 'Share on Facebook' },
  'share.pinterest': { fr: 'Épingler sur Pinterest', en: 'Pin on Pinterest' },
  'legal.privacy.title': { fr: 'Politique de confidentialité', en: 'Privacy Policy' },
  'legal.terms.title': { fr: "Conditions d'utilisation", en: 'Terms of Use' },
  'home.hero.subtitle': {
    fr: 'Des centaines de coloriages originaux pour les enfants. Téléchargez, imprimez et coloriez !',
    en: 'Hundreds of original coloring pages for kids. Download, print and color!',
  },
  'home.empty': {
    fr: 'Les coloriages arrivent bientôt ! Revenez nous voir.',
    en: 'Coloring pages coming soon! Check back later.',
  },
  'category.description': {
    fr: 'Découvrez nos coloriages {label} gratuits à imprimer.',
    en: 'Discover our free printable {label} coloring pages.',
  },
  'category.empty': {
    fr: 'Les coloriages {label} arrivent bientôt !',
    en: '{label} coloring pages coming soon!',
  },
  'categories.title': {
    fr: 'Toutes les Catégories',
    en: 'All Categories',
  },
  'categories.description': {
    fr: 'Parcourez toutes nos catégories de coloriages gratuits à imprimer.',
    en: 'Browse all our free printable coloring page categories.',
  },
  'categories.count': {
    fr: '{count} coloriages',
    en: '{count} coloring pages',
  },
  'categories.explore': {
    fr: 'Voir les coloriages',
    en: 'View coloring pages',
  },
  'home.nouveaux.title': {
    fr: 'Nouveaux Coloriages',
    en: 'New Coloring Pages',
  },
  'home.nouveaux.subtitle': {
    fr: 'Les derniers ajoutés',
    en: 'Latest additions',
  },
  'home.filter.all': { fr: 'Tous', en: 'All' },
  'category.description.adults': {
    fr: 'Découvrez nos coloriages {label} gratuits à imprimer pour adultes.',
    en: 'Discover our free printable {label} coloring pages for adults.',
  },
  'category.animaux.seoText': {
    fr: "Les coloriages animaux sont parmi les plus appréciés de notre collection. Que votre enfant soit passionné par les lions de la savane, les dauphins des océans ou les lapins de la maison, vous trouverez ici des dizaines de modèles à imprimer gratuitement. Notre sélection couvre l'ensemble du règne animal : animaux sauvages d'Afrique et d'Asie (éléphants, tigres, girafes, rhinocéros), animaux de la ferme (vaches, cochons, poules, chevaux), animaux domestiques (chats, chiens, lapins, perroquets) et créatures marines (dauphins, requins, tortues marines, étoiles de mer). Colorier des animaux présente de nombreux avantages pédagogiques : les enfants apprennent à reconnaître les espèces, découvrent leurs habitats naturels et développent leur sensibilité à la nature et à la biodiversité. C'est aussi une activité ludique qui renforce la concentration et améliore la motricité fine. Les grands peuvent choisir des coloriages plus détaillés avec les textures des plumes, des écailles ou de la fourrure. Les petits apprécieront des dessins aux contours simples et aux formes rondes. Tous nos coloriages animaux sont disponibles au format A4, imprimables gratuitement depuis n'importe quel appareil. Imprimez-les pour des activités à la maison, en classe ou lors d'ateliers créatifs en famille.",
    en: "Animal coloring pages are among the most popular in our collection, loved by children of all ages. Whether your child is fascinated by lions on the savanna, dolphins in the ocean, or the family dog at home, you'll find dozens of free printable illustrations here. Our selection covers the entire animal kingdom: wild animals from Africa and Asia (elephants, tigers, giraffes, rhinos), farm animals (cows, pigs, chickens, horses), domestic pets (cats, dogs, rabbits, parrots), and sea creatures (dolphins, sharks, sea turtles, starfish). Coloring animals offers multiple educational benefits: children learn to recognize and name species, discover their natural habitats, and develop a love for nature and biodiversity. It's also a fun activity that strengthens concentration and improves fine motor skills. Older children can choose more detailed illustrations featuring feather textures, scales, or fur patterns. Younger ones will enjoy drawings with simple outlines and rounded shapes. All our animal coloring pages are available in A4 format, free to print from any device. Print them for home activities, classroom workshops, or creative family outings.",
  },
  'category.vehicules.seoText': {
    fr: "Voitures de course, camions de pompier, avions à réaction, vaisseaux spatiaux — notre collection de coloriages véhicules ravira tous les enfants passionnés de machines et de transport. Chaque coloriage est dessiné avec précision pour représenter fidèlement les détails de chaque véhicule tout en restant accessible aux jeunes coloristes. Nos catégories couvrent l'ensemble des modes de transport : la route (voitures, camions, motos, bus, taxis), le rail (trains à vapeur, TGV, tramways, métros), les airs (avions de ligne, hélicoptères, montgolfières) et la mer (bateaux à voile, paquebots, sous-marins). Sans oublier les véhicules spéciaux : ambulances, camions de pompier, tracteurs agricoles et engins de chantier que les enfants adorent. Colorier des véhicules est une excellente activité pour développer la motricité fine et la concentration. C'est aussi une porte d'entrée vers l'apprentissage : comment fonctionne un moteur ? Quelle est la différence entre un avion et un hélicoptère ? Les enfants apprennent en jouant. Nos coloriages véhicules sont disponibles gratuitement en format A4 haute résolution, prêts à imprimer en un clic. Parfaits pour les anniversaires sur le thème des voitures, les activités scolaires ou simplement pour occuper les enfants lors de longs trajets.",
    en: "Race cars, fire trucks, jet planes, space shuttles — our vehicle coloring pages will delight every child passionate about machines and transportation. Each illustration is drawn with precision to faithfully represent the details of each vehicle while remaining accessible to young artists. Our categories cover all modes of transport: road (cars, trucks, motorcycles, buses, taxis), rail (steam trains, high-speed trains, trams, subways), air (airliners, helicopters, hot air balloons), and sea (sailboats, cruise ships, submarines, aircraft carriers). Not forgetting special vehicles: ambulances, fire trucks, farm tractors, and construction equipment that children adore. Coloring vehicles is an excellent activity for developing fine motor skills and concentration. It's also a gateway to learning: how does a motor work? What's the difference between a plane and a helicopter? Children learn while having fun. Our vehicle coloring pages are available for free in A4 high-resolution format, ready to print with one click. Perfect for car-themed birthday parties, school activities, or simply keeping children busy during long road trips.",
  },
  'category.nature.seoText': {
    fr: "La nature offre une palette de couleurs infinie, et nos coloriages nature en capturent toute la beauté. Fleurs des champs, arbres centenaires, champignons enchantés, paysages de montagne : notre collection permet aux enfants d'explorer et de s'approprier le monde végétal et naturel. Découvrez des roses et des tournesols pour les amoureux de jardinage, des forêts mystérieuses pour les amateurs de fantastique, des fonds marins luxuriants pour les explorateurs des océans. Nos coloriages nature incluent aussi des scènes de saisons : cerisiers en fleurs du printemps, forêts d'automne aux tons orangés, plages ensoleillées de l'été et paysages enneigés de l'hiver. Colorier la nature sensibilise les enfants à l'environnement et à la biodiversité. En choisissant les couleurs d'une fleur ou d'un arbre, ils apprennent que chaque plante a ses propres couleurs, que les feuilles changent en automne, que les fleurs attirent les abeilles et les papillons. C'est une éducation à l'écologie par le dessin. Nos coloriages nature sont gratuits, disponibles au format A4 et prêts à imprimer. Ils conviennent aussi bien aux enfants qu'aux adultes qui souhaitent se reconnecter à la beauté de la nature par le dessin et la créativité.",
    en: "Nature offers an infinite palette of colors, and our nature coloring pages capture all its beauty. Meadow flowers, century-old trees, enchanted mushrooms, mountain landscapes — our collection lets children explore and connect with the plant and natural world. Discover roses and sunflowers for gardening lovers, mysterious forests for fantasy fans, lush seabeds for ocean explorers. Our nature coloring pages also include seasonal scenes: spring cherry blossoms, autumn forests in golden and orange tones, sunny summer beaches, and snowy winter landscapes. Coloring nature raises children's awareness of the environment and biodiversity. By choosing the colors of a flower or tree, they learn that each plant has its own colors, that leaves change in autumn, that flowers attract bees and butterflies. It's an education in ecology through drawing. Our nature coloring pages are free, available in A4 format, and ready to print. They are suitable for both children and adults who wish to reconnect with the beauty of nature through drawing and creativity.",
  },
  'category.alphabet.seoText': {
    fr: "Apprendre l'alphabet devient un jeu d'enfant avec nos coloriages éducatifs ! Chaque lettre est associée à un dessin amusant qui aide les enfants à mémoriser l'alphabet tout en s'amusant. Le A comme Ananas, le B comme Ballon, le C comme Chat — nos coloriages alphabet suivent cette logique mnémotechnique qui facilite l'apprentissage de la lecture et de l'écriture. Notre collection propose des coloriages pour toutes les lettres, de A à Z, avec des dessins soigneusement choisis pour être immédiatement reconnaissables par les jeunes enfants. Les lettres sont tracées en grands caractères, idéales pour que les enfants apprennent aussi à les écrire en les repassant au crayon. Ces coloriages sont des outils pédagogiques précieux pour les parents et les enseignants de maternelle et de CP. Ils permettent d'associer l'aspect visuel de chaque lettre à une image mémorable, renforçant ainsi l'apprentissage de manière durable. En plus de l'aspect éducatif, colorier les lettres développe la motricité fine, la coordination œil-main et la concentration — des compétences essentielles pour l'apprentissage scolaire. Tous nos coloriages alphabet sont disponibles gratuitement au format A4. Imprimez-les pour les utiliser à la maison ou en classe, comme support de jeu ou comme exercice d'écriture.",
    en: "Learning the alphabet becomes child's play with our educational coloring pages! Each letter is paired with a fun drawing that helps children memorize the alphabet while having fun. A for Apple, B for Ball, C for Cat — our alphabet coloring pages follow this mnemonic logic that makes learning to read and write easier. Our collection offers coloring pages for every letter, from A to Z, with illustrations carefully chosen to be immediately recognizable by young children. The letters are drawn in large characters, ideal for children to also practice writing by tracing them. These coloring pages are valuable educational tools for parents and preschool and kindergarten teachers. They allow each letter's visual form to be associated with a memorable image, reinforcing learning in a lasting way. Beyond the educational aspect, coloring letters develops fine motor skills, hand-eye coordination, and concentration — essential skills for school learning. All our alphabet coloring pages are available for free in A4 format. Print them for use at home or in the classroom, as play supports or writing exercises.",
  },
  'category.dinosaures.seoText': {
    fr: "Partez à la conquête du Jurassique avec nos coloriages dinosaures ! Notre collection réunit tous les géants préhistoriques que les enfants adorent : le redoutable Tyrannosaurus Rex aux immenses mâchoires, le long et paisible Diplodocus, le Tricératops avec ses trois cornes impressionnantes, le Stégosaure avec ses plaques dorsales et le Vélociraptor agile et intelligent. Nos dessins sont réalisés avec précision scientifique tout en restant accessibles aux jeunes artistes. Les enfants peuvent laisser libre cours à leur imagination : les dinosaures étaient-ils verts, bleus, rouges ? Personne ne sait vraiment, alors tout est permis ! Les coloriages dinosaures sont une porte d'entrée fascinante vers la paléontologie et l'histoire de la vie sur Terre. En coloriant leur T-Rex préféré, les enfants apprennent que ces créatures gigantesques ont réellement existé il y a des millions d'années, ouvrant la discussion sur l'évolution des espèces et les extinctions de masse. Ces coloriages stimulent la curiosité scientifique et le goût pour la découverte du monde naturel. Nos coloriages dinosaures sont disponibles gratuitement en format A4 haute résolution. Imprimez-les pour des activités passionnantes à la maison, en classe ou lors d'anniversaires sur le thème préhistorique.",
    en: "Embark on a Jurassic adventure with our dinosaur coloring pages! Our collection brings together all the prehistoric giants children love: the fearsome Tyrannosaurus Rex with its massive jaws, the long and peaceful Diplodocus, the Triceratops with its three impressive horns, the Stegosaurus with its dorsal plates, and the agile, intelligent Velociraptor. Our illustrations are made with scientific accuracy while remaining accessible to young artists. Children can let their imagination run wild — were dinosaurs green, blue, or red? Nobody really knows, so anything goes! Dinosaur coloring pages are a fascinating gateway to paleontology and the history of life on Earth. By coloring their favorite T-Rex, children learn that these gigantic creatures actually existed millions of years ago, opening discussions about evolution and mass extinctions. These pages spark scientific curiosity and a love for exploring the natural world. Our dinosaur coloring pages are available for free in A4 high-resolution format. Print them for exciting activities at home, in the classroom, or for prehistoric-themed birthday parties.",
  },
  'category.super-heros.seoText': {
    fr: "Enfilez la cape et partez sauver le monde avec nos coloriages super-héros ! Notre collection rassemble des dizaines de héros aux pouvoirs extraordinaires dans des poses d'action dynamiques : le super-héros volant qui protège la ville depuis les airs, l'homme araignée qui escalade les immeubles, la super-héroïne invincible qui affronte les ennemis. Les costumes colorés, les capes flottantes et les emblèmes distinctifs offrent de nombreuses surfaces à colorier. Les enfants peuvent reproduire les couleurs classiques de leurs archétypes préférés ou inventer de nouvelles tenues pour des héros totalement originaux. Les coloriages super-héros développent la créativité et l'imagination tout en permettant aux enfants d'explorer des thèmes importants comme le courage, la justice et la responsabilité. Créer son propre super-héros — lui inventer un nom, des pouvoirs, une histoire — est une activité narrative riche qui stimule le développement cognitif et émotionnel. Ces coloriages sont parfaits pour les anniversaires sur le thème des super-héros, les fêtes costumées et les ateliers créatifs en classe. Nos coloriages super-héros sont disponibles gratuitement en format A4 haute résolution. Imprimez-les pour des heures de jeu créatif à la maison ou en groupe.",
    en: "Put on your cape and save the world with our superhero coloring pages! Our collection features dozens of heroes with extraordinary powers in dynamic action poses: the flying superhero protecting the city from the air, the spider-man scaling buildings, the invincible superheroine taking on enemies. Colorful costumes, flowing capes, and distinctive emblems provide plenty of surfaces to color. Children can reproduce the classic colors of their favorite archetypes or invent new outfits for completely original heroes. Superhero coloring pages develop creativity and imagination while allowing children to explore important themes like courage, justice, and responsibility. Creating your own superhero — inventing a name, powers, and backstory — is a rich narrative activity that stimulates cognitive and emotional development. These coloring pages are perfect for superhero-themed birthday parties, costume events, and creative classroom workshops. Our superhero coloring pages are available for free in A4 high-resolution format. Print them for hours of creative play at home or in groups.",
  },
  'category.espace.seoText': {
    fr: "Décollage immédiat pour l'aventure spatiale ! Nos coloriages espace transportent les enfants dans les confins du cosmos, à la rencontre des planètes du système solaire, des étoiles lointaines et des mystérieux extraterrestres. Explorez Saturne et ses anneaux magnifiques, Jupiter et ses tempêtes géantes, Mars la planète rouge, ou encore la Lune criblée de cratères. Nos dessins représentent aussi les vaisseaux spatiaux, des navettes de la NASA aux fusées futuristes en passant par les rovers martiens, et bien sûr les astronautes en combinaison spatiale flottant dans l'apesanteur. Les coloriages espace sont une formidable introduction à l'astronomie pour les enfants. En coloriant les planètes, ils apprennent leurs noms, leur ordre dans le système solaire et leurs caractéristiques distinctives. C'est une façon ludique de découvrir les sciences et de nourrir la curiosité pour l'univers. Ces coloriages stimulent également l'imagination : et si des extraterrestres vivaient sur d'autres planètes ? À quoi ressemblerait une cité sur Mars ? Les questions que soulèvent ces dessins ouvrent de belles discussions parent-enfant. Nos coloriages espace sont disponibles gratuitement en format A4. Imprimez-les pour des activités créatives à la maison, en classe de sciences ou lors de soirées d'observation des étoiles.",
    en: "Immediate takeoff for space adventure! Our space coloring pages transport children to the far reaches of the cosmos, where they'll encounter solar system planets, distant stars, and mysterious aliens. Explore Saturn with its magnificent rings, Jupiter with its giant storms, red planet Mars, and the crater-filled Moon. Our illustrations also feature spacecraft — from NASA shuttles to futuristic rockets and Mars rovers — plus astronauts in space suits floating in zero gravity. Space coloring pages are a fantastic introduction to astronomy for children. By coloring the planets, they learn their names, their order in the solar system, and their distinctive features. It's a fun way to discover science and fuel curiosity about the universe. These pages also spark imagination: what if aliens lived on other planets? What would a city on Mars look like? The questions these drawings raise open wonderful parent-child conversations. Our space coloring pages are available for free in A4 format. Print them for creative activities at home, in science class, or during stargazing evenings.",
  },
  'category.princesses-chevaliers.seoText': {
    fr: "Bienvenue dans le monde enchanté des princesses et des chevaliers ! Notre collection de coloriages transporte les enfants dans des royaumes féeriques peuplés de belles princesses courageuses, de vaillants chevaliers, de châteaux majestueux et de dragons cracheurs de feu. Les princesses de notre collection ont chacune leur personnalité unique : guerrière intrépide, magicienne érudite ou diplomate qui négocie la paix entre royaumes. Les chevaliers affrontent dragons et sorciers pour accomplir des quêtes épiques et protéger leurs amis. Ces coloriages permettent aux enfants de donner vie à des histoires fantastiques. En choisissant les couleurs de la robe d'une princesse ou de l'armure d'un chevalier, ils construisent des personnages et inventent leurs propres aventures. C'est une activité qui développe la créativité narrative et l'imagination. Les dessins aux lignes claires et aux détails soignés conviennent aux enfants de 4 à 10 ans. Les plus jeunes apprécieront les contours simples, tandis que les plus grands pourront s'amuser à colorier les ornements complexes des costumes et les décors des châteaux. Nos coloriages princesses et chevaliers sont disponibles gratuitement au format A4. Parfaits pour des anniversaires thématiques ou des activités créatives en famille.",
    en: "Welcome to the enchanted world of princesses and knights! Our coloring collection transports children to magical kingdoms filled with brave princesses, valiant knights, majestic castles, and fire-breathing dragons. The princesses in our collection each have their own unique personality: the fearless warrior, the learned sorceress, or the diplomat who negotiates peace between kingdoms. Knights face dragons and sorcerers to accomplish epic quests and protect their friends. These coloring pages allow children to bring fantastic stories to life. By choosing the colors for a princess's gown or a knight's armor, they build characters and invent their own adventures. It's an activity that develops narrative creativity and imagination. Illustrations with clear lines and careful details suit children ages 4 to 10. Younger children will enjoy simple outlines, while older ones can have fun coloring the intricate ornaments of costumes and castle decorations. Our princess and knight coloring pages are available for free in A4 format. Perfect for themed birthday parties or creative family activities.",
  },
  'category.metiers.seoText': {
    fr: "Nos coloriages métiers aident les enfants à découvrir la diversité des professions et à explorer leurs envies de futur. Pompier courageux, médecin attentionné, chef cuisinier créatif, architecte visionnaire, astronaute explorateur : notre collection présente des dizaines de métiers sous forme de dessins attractifs à colorier. Chaque coloriage illustre un professionnel en action avec les outils typiques de son métier : la hache et le casque du pompier, le stéthoscope du médecin, la toque et la spatule du cuisinier, l'équerre et le compas de l'architecte. Ces coloriages ont une vraie valeur éducative : ils permettent d'initier des conversations sur les métiers, l'importance de chaque rôle dans la société et les formations nécessaires. C'est une façon ludique d'éveiller les vocations et de valoriser tous les corps de métier, des plus connus aux moins visibles. Les jeux de rôle autour de ces coloriages — jouer au médecin, au pompier, au chef — renforcent l'apprentissage et favorisent le développement social et émotionnel des enfants. Nos coloriages métiers sont disponibles gratuitement au format A4. Idéaux pour les activités de classe sur les professions ou les jeux de rôle éducatifs à la maison.",
    en: "Our job coloring pages help children discover the diversity of professions and explore their dreams for the future. Brave firefighter, caring doctor, creative chef, visionary architect, exploring astronaut — our collection features dozens of jobs as attractive coloring illustrations. Each page depicts a professional in action with the typical tools of their trade: the axe and helmet of the firefighter, the doctor's stethoscope, the chef's toque and spatula, the architect's square and compass. These coloring pages have real educational value: they open conversations about careers, the importance of each role in society, and the education required. It's a fun way to spark vocational interest and celebrate all professions, from the most well-known to the less visible. Role-playing games around these pages — playing doctor, firefighter, or chef — reinforce learning and support children's social and emotional development. Our job coloring pages are available for free in A4 format. Ideal for classroom activities about careers or educational role-playing games at home.",
  },
  'category.sport.seoText': {
    fr: "Le sport, c'est l'aventure, le dépassement de soi et le plaisir en équipe ! Nos coloriages sport célèbrent toutes les disciplines sportives que les enfants pratiquent et admirent. Football, natation, tennis, cyclisme, gymnastique, basketball, judo, rugby : notre collection couvre un large éventail de sports pour que chaque enfant trouve son activité préférée à colorier. Nos dessins mettent en scène des athlètes en pleine action : le footballeur qui marque un but, la gymnaste qui effectue un saut périlleux, le nageur qui plonge dans la piscine, le cycliste qui dévale une descente. Ces images dynamiques donnent de l'énergie et encouragent les enfants à pratiquer des activités physiques. Les coloriages sport peuvent aussi accompagner les grands événements sportifs. Pendant la Coupe du Monde, les Jeux Olympiques ou le Tour de France, imprimez les dessins correspondants pour créer de l'enthousiasme et des activités créatives en lien avec l'actualité. C'est une façon ludique d'initier les enfants à ces événements mondiaux et aux valeurs du sport : effort, fair-play, persévérance et esprit d'équipe. Nos coloriages sport sont disponibles gratuitement en format A4. Parfaits pour les associations sportives, les écoles ou simplement pour les familles qui partagent leur passion pour le sport.",
    en: "Sport is adventure, self-improvement, and team fun! Our sport coloring pages celebrate all the athletic disciplines children practice and admire. Soccer, swimming, tennis, cycling, gymnastics, basketball, judo, rugby — our collection covers a wide range of sports so every child finds their favorite activity to color. Our illustrations depict athletes in full action: the soccer player scoring a goal, the gymnast performing a somersault, the swimmer diving into the pool, the cyclist racing down a descent. These dynamic images are energizing and encourage children to be physically active. Sport coloring pages can also accompany major sporting events. During the World Cup, the Olympics, or the Tour de France, print the corresponding illustrations to create excitement and creative activities tied to current events. It's a fun way to introduce children to these world events and the values of sport: effort, fair play, perseverance, and team spirit. Our sport coloring pages are available for free in A4 format. Perfect for sports clubs, schools, or simply families who share a passion for sports.",
  },
  'category.saisons.seoText': {
    fr: "Les quatre saisons offrent une ronde de couleurs et d'ambiances tout au long de l'année. Nos coloriages saisons capturent la magie de chaque période : les cerisiers en fleurs et les jonquilles du printemps, les plages ensoleillées et les glaces fondantes de l'été, les feuilles d'automne aux teintes dorées et orangées, les flocons de neige et les bonshommes de neige de l'hiver. Chaque saison est représentée par plusieurs scènes emblématiques qui permettent aux enfants d'explorer les cycles de la nature. Les coloriages saisons sont d'excellents supports pédagogiques pour parler du temps qui passe, des changements climatiques, des habitudes des animaux selon les saisons (migration, hibernation) et des activités humaines liées à chaque période de l'année. En automne, colorier les feuilles tombées et les châtaignes. En hiver, donner vie à des scènes enneigées. Au printemps, faire éclore les fleurs. En été, peindre des scènes de vacances. Ces coloriages rythment l'année scolaire et accompagnent les enfants dans leur apprentissage du temps et du calendrier. Nos coloriages saisons sont disponibles gratuitement au format A4. Idéaux pour une utilisation en classe à chaque changement de saison ou pour des activités créatives en famille tout au long de l'année.",
    en: "The four seasons offer a parade of colors and atmospheres throughout the year. Our seasons coloring pages capture the magic of each period: spring cherry blossoms and daffodils, sunny summer beaches and melting ice cream, autumn leaves in golden and orange hues, snowflakes and snowmen of winter. Each season is represented by several iconic scenes that let children explore nature's cycles. Seasons coloring pages are excellent educational tools for discussing the passing of time, climate patterns, animal behaviors by season (migration, hibernation), and human activities tied to each time of year. In autumn, color fallen leaves and chestnuts. In winter, bring snowy scenes to life. In spring, make flowers bloom. In summer, paint holiday scenes. These pages give rhythm to the school year and accompany children in learning about time and the calendar. Our seasons coloring pages are available for free in A4 format. Ideal for classroom use at each change of season or for creative family activities throughout the year.",
  },
  'category.fetes.seoText': {
    fr: "Noël, Pâques, Halloween, les anniversaires : les fêtes sont des moments de joie collective que nos coloriages capturent avec éclat. Notre collection fêtes rassemble des dizaines de dessins à colorier pour célébrer toutes les occasions importantes de l'année. Pour Noël, retrouvez le Père Noël et son traîneau, les rennes, les étoiles et les sapins décorés. Pour Pâques, colorisez des lapins en chocolat, des œufs décorés et des petits poussins. Pour Halloween, donnez vie à des citrouilles effrayantes, des fantômes rigolots et des sorcières en balai. Pour les anniversaires, nos dessins de gâteaux, ballons et bougies créeront l'ambiance parfaite. Les coloriages de fête ont une place particulière dans le cœur des enfants car ils accompagnent les moments les plus heureux de leur vie. Colorier un Père Noël la veille de Noël ou décorer une citrouille avant Halloween crée des souvenirs et des traditions familiales durables. Ces activités créatives permettent aux enfants de s'impliquer activement dans les préparatifs des fêtes et de contribuer à la magie des moments familiaux. Nos coloriages fêtes sont disponibles gratuitement au format A4. Téléchargez-les avant chaque occasion pour créer des activités créatives mémorables avec vos enfants.",
    en: "Christmas, Easter, Halloween, birthdays — holidays are moments of collective joy that our coloring pages capture brilliantly. Our holiday collection brings together dozens of coloring illustrations to celebrate all the important occasions of the year. For Christmas, find Santa Claus and his sleigh, reindeer, stars, and decorated trees. For Easter, color chocolate bunnies, decorated eggs, and baby chicks. For Halloween, bring to life scary pumpkins, funny ghosts, and witches on broomsticks. For birthdays, our cakes, balloons, and candles illustrations will create the perfect atmosphere. Holiday coloring pages hold a special place in children's hearts because they accompany the happiest moments of their lives. Coloring Santa Claus on Christmas Eve or decorating a pumpkin before Halloween creates lasting memories and family traditions. These creative activities allow children to actively participate in holiday preparations and contribute to the magic of family moments. Our holiday coloring pages are available for free in A4 format. Download them before each occasion to create memorable creative activities with your children.",
  },
  'category.personnages.seoText': {
    fr: "Les personnages de fiction captivent l'imagination des enfants depuis toujours. Notre collection de coloriages personnages réunit des héros originaux créés par nos illustrateurs : petits garçons et petites filles courageux, créatures fantastiques bienveillantes, animaux anthropomorphes pleins de sagesse. Chaque personnage a sa propre histoire et son propre univers visuel, invitant les enfants à créer et imaginer des aventures. Les dessins proposés couvrent une variété de styles graphiques : personnages ronds et mignons pour les plus petits, silhouettes plus détaillées pour les enfants plus grands. Certains personnages sont représentés seuls, d'autres en scènes avec leurs amis, permettant aux enfants de colorier des histoires entières. La création de personnages est l'une des activités créatives les plus enrichissantes pour les enfants. En choisissant les couleurs de la tenue d'un personnage, de ses yeux et de ses cheveux, l'enfant s'approprie le personnage et lui invente une identité. C'est le début de la narration créative et de l'écriture imaginative. Ces coloriages s'accompagnent naturellement d'activités de conte et d'écriture : quel est le nom de ce personnage ? Où habite-t-il ? Quelle est son aventure ? Nos coloriages personnages sont disponibles gratuitement au format A4, idéaux pour stimuler l'imagination des enfants.",
    en: "Fictional characters have always captivated children's imaginations. Our character coloring pages bring together original heroes created by our illustrators: brave boys and girls, benevolent fantasy creatures, wise anthropomorphic animals. Each character has their own story and visual world, inviting children to create and imagine adventures. The illustrations cover a variety of graphic styles: round and cute characters for younger children, more detailed silhouettes for older ones. Some characters appear alone, others in scenes with friends, allowing children to color entire stories. Character creation is one of the most enriching creative activities for children. By choosing the colors for a character's outfit, eyes, and hair, children claim the character and invent their identity. This is the beginning of creative storytelling and imaginative writing. These coloring pages naturally accompany storytelling and writing activities: what is this character's name? Where do they live? What is their adventure? Our character coloring pages are available for free in A4 format, perfect for sparking children's imagination.",
  },
  'category.contes.seoText': {
    fr: "Il était une fois... une collection de coloriages dédiée aux contes et aux histoires qui bercent l'enfance depuis des générations. Cendrillon, Blanche-Neige, le Petit Chaperon Rouge, Jack et le Haricot Magique, les Trois Petits Cochons, Pinocchio : les héros des grands contes classiques prennent vie dans nos illustrations à colorier. Nos dessins représentent les scènes les plus emblématiques de ces histoires intemporelles : la pantoufle de verre, la Belle dormant dans son château, le Chaperon Rouge rencontrant le Grand Méchant Loup. Les enfants qui connaissent ces histoires prennent un plaisir particulier à colorier les personnages qu'ils imaginaient depuis leurs premières lectures. Les coloriages contes sont d'excellents supports pour accompagner la lecture à voix haute. Après avoir lu ou raconté l'histoire, proposez aux enfants de colorier leurs personnages préférés : c'est une façon de prolonger le plaisir de la lecture et de vérifier leur compréhension de l'histoire. Ces coloriages renforcent l'amour de la littérature et sensibilisent les enfants à la richesse du patrimoine culturel. Nos coloriages contes sont disponibles gratuitement au format A4. Parfaits pour les coins lecture, les bibliothèques scolaires ou les activités de lecture en famille.",
    en: "Once upon a time... a coloring collection dedicated to fairy tales and stories that have shaped childhood for generations. Cinderella, Snow White, Little Red Riding Hood, Jack and the Beanstalk, The Three Little Pigs, Pinocchio — the heroes of great classic fairy tales come to life in our coloring illustrations. Our drawings depict the most iconic scenes from these timeless stories: the glass slipper, Sleeping Beauty in her castle, Little Red Riding Hood meeting the Big Bad Wolf. Children who know these stories take particular delight in coloring the characters they have imagined since their first readings. Fairy tale coloring pages are excellent supports for read-aloud activities. After reading or telling the story, invite children to color their favorite characters — it's a way to extend the pleasure of reading and check their understanding. These coloring pages strengthen love of literature and introduce children to the richness of cultural heritage. Our fairy tale coloring pages are available for free in A4 format. Perfect for reading corners, school libraries, or family reading activities.",
  },
  'category.drole.seoText': {
    fr: "Rires, grimaces et situations absurdes garantis ! Nos coloriages drôles sont conçus pour faire sourire les enfants tout en les invitant à colorier des personnages hilarants dans des situations comiques. Des animaux qui font des blagues, des personnages aux expressions exagérées, des scènes inattendues et des situations absurdes : notre collection humoristique est un concentré de bonne humeur. Le dessin humoristique a ses propres codes graphiques : les expressions faciales exagérées, les yeux en spirale, les personnages qui tombent, les éclairs de colère stylisés. En coloriant ces dessins, les enfants apprennent à lire les émotions dans les visages et à comprendre les mécanismes du comique visuel. L'humour est une dimension importante du développement de l'enfant. Comprendre pourquoi quelque chose est drôle, apprécier l'absurde, créer ses propres blagues : ce sont des étapes importantes du développement cognitif et social. Les coloriages drôles offrent un contexte léger et joyeux pour explorer ces dimensions. Ces coloriages sont parfaits pour égayer une journée maussade, décorer la chambre d'un enfant ou créer des cartes de vœux originales et rigolotes. Nos coloriages drôles sont disponibles gratuitement au format A4. Imprimez-les pour des fous rires garantis et des souvenirs créatifs inoubliables.",
    en: "Laughter, silly faces, and absurd situations guaranteed! Our funny coloring pages are designed to make children smile while inviting them to color hilarious characters in comic situations. Joke-telling animals, characters with exaggerated expressions, unexpected scenes, and absurd situations — our humor collection is a concentration of good cheer. Comic drawing has its own visual codes: exaggerated facial expressions, spiral eyes, falling characters, stylized anger lightning bolts. By coloring these drawings, children learn to read emotions in faces and understand the mechanisms of visual comedy. Humor is an important dimension of a child's development. Understanding why something is funny, appreciating the absurd, creating their own jokes — these are important steps in cognitive and social development. Funny coloring pages offer a light and joyful context to explore these dimensions. These pages are perfect for brightening a gloomy day, decorating a child's room, or creating original and amusing greeting cards. Our funny coloring pages are available for free in A4 format. Print them for guaranteed laughter and unforgettable creative memories.",
  },
  'category.mandalas.seoText': {
    fr: "Les mandalas sont bien plus que de simples dessins à colorier : ce sont des œuvres d'art géométriques aux vertus méditatives reconnues. Issu des traditions hindoue et bouddhiste, le mandala représente l'univers et l'équilibre. Nos coloriages mandalas pour adultes proposent une large gamme de motifs, des plus simples aux plus élaborés, pour tous les niveaux de pratique. La répétition de motifs géométriques en cercles concentriques crée un effet hypnotique propice à la concentration et à la relaxation. Colorier un mandala permet de se déconnecter du stress quotidien, de ralentir le rythme et de se concentrer sur le moment présent — une forme de méditation active accessible à tous. De nombreux thérapeutes recommandent le coloriage de mandalas comme outil anti-stress. Contrairement à d'autres formes d'art qui requièrent un apprentissage technique, les mandalas sont accessibles à tous : aucune compétence artistique n'est nécessaire pour commencer. Nos mandalas adultes couvrent un large spectre de complexité : des motifs floraux simples pour les débutants aux entrelacs géométriques complexes pour les experts. Choisissez vos crayons, feutres ou aquarelles, et laissez-vous porter par le flux créatif. Nos coloriages mandalas sont disponibles gratuitement au format A4 haute résolution, prêts à imprimer pour votre prochain moment de détente.",
    en: "Mandalas are much more than simple coloring pages: they are geometric artworks with recognized meditative virtues. Originating from Hindu and Buddhist traditions, the mandala represents the universe and balance. Our adult mandala coloring pages offer a wide range of patterns, from the simplest to the most elaborate, for all skill levels. The repetition of geometric motifs in concentric circles creates a hypnotic effect conducive to concentration and relaxation. Coloring a mandala allows you to disconnect from daily stress, slow down, and focus on the present moment — a form of active meditation accessible to everyone. Many therapists recommend mandala coloring as an anti-stress tool. Unlike other art forms that require technical training, mandalas are accessible to all: no artistic skill is needed to begin. Our adult mandalas span a wide complexity spectrum: simple floral patterns for beginners to intricate geometric weaves for experts. Choose your colored pencils, markers, or watercolors, and let yourself be carried by the creative flow. Our mandala coloring pages are available for free in A4 high-resolution format, ready to print for your next relaxation session.",
  },
  'category.mosaiques.seoText': {
    fr: "Les mosaïques sont l'un des arts les plus anciens de l'humanité, de l'Antiquité romaine aux azulejos portugais en passant par les zellige marocains. Nos coloriages mosaïques pour adultes s'inspirent de ces traditions artistiques millénaires pour proposer des motifs géométriques à colorier, case par case, comme un vrai artisan mosaïste. Chaque coloriage mosaïque est composé de petites cellules — carrées, hexagonales, triangulaires ou irrégulières — que vous remplissez de couleurs selon votre inspiration. Le résultat final est une œuvre d'art nuancée et harmonieuse, dont l'effet d'ensemble ne se révèle qu'une fois toutes les cases colorées. Cette approche analytique du coloriage est particulièrement satisfaisante et méditative. Elle nécessite de la patience et de la précision, mais chaque petite zone colorée représente un micro-accomplissement qui nourrit la satisfaction créative. Les mosaïques permettent aussi d'explorer la théorie des couleurs : l'harmonie des teintes voisines, les contrastes entre couleurs complémentaires, les effets de dégradé. C'est une façon de pratiquer des notions artistiques avancées dans un cadre ludique et accessible. Nos coloriages mosaïques sont disponibles gratuitement au format A4 haute résolution. Utilisez des feutres fins pour les petites cases et des crayons de couleur pour les plus grandes surfaces.",
    en: "Mosaics are one of humanity's oldest art forms, from Roman antiquity to Portuguese azulejos and Moroccan zellige. Our adult mosaic coloring pages draw inspiration from these millennia-old artistic traditions to offer geometric patterns to color cell by cell, like a true mosaic craftsman. Each mosaic coloring page is composed of small cells — square, hexagonal, triangular, or irregular — that you fill with colors according to your inspiration. The final result is a nuanced and harmonious artwork, whose overall effect only reveals itself once all cells are colored. This analytical approach to coloring is particularly satisfying and meditative. It requires patience and precision, but each small colored area represents a micro-achievement that feeds creative satisfaction. Mosaics also allow you to explore color theory: the harmony of neighboring hues, contrasts between complementary colors, gradient effects. It's a way to practice advanced artistic concepts in a fun and accessible setting. Our mosaic coloring pages are available for free in A4 high-resolution format. Use fine-tipped markers for small cells and colored pencils for larger areas.",
  },
  'category.abstrait.seoText': {
    fr: "L'art abstrait libère l'imagination de toute contrainte réaliste. Dans nos coloriages abstraits pour adultes, il n'y a pas de représentation d'objets ou de personnages reconnaissables : seulement des formes, des lignes, des courbes et des espaces à remplir selon votre propre vision. Chaque coloriage abstrait est une invitation à l'exploration créative sans règles ni contraintes. Vous pouvez choisir une palette monochrome pour un effet épuré et contemporain, ou opter pour des couleurs vives et contrastées pour un résultat éclatant et dynamique. Le résultat sera unique, reflet de votre sensibilité artistique du moment. L'art abstrait est libérateur car il n'y a pas de mauvaise façon de le colorier. Contrairement aux coloriages figuratifs où vous pouvez vous demander « le ciel doit-il être bleu ? », l'abstrait répond : colorez comme vous le sentez. Cette liberté totale est particulièrement bénéfique pour les adultes qui ont tendance à s'autocensurer artistiquement. Les coloriages abstraits sont aussi d'excellents objets décoratifs une fois terminés : encadrés, ils forment de beaux tableaux originaux pour décorer votre intérieur. Nos coloriages abstraits sont disponibles gratuitement au format A4. Imprimez-les sur du beau papier pour un rendu optimal et accrochez vos créations avec fierté.",
    en: "Abstract art frees the imagination from all realistic constraints. In our adult abstract coloring pages, there are no recognizable objects or characters — only shapes, lines, curves, and spaces to fill according to your own vision. Each abstract coloring page is an invitation to creative exploration with no rules or constraints. You can choose a monochrome palette for a clean, contemporary effect, or opt for bright, contrasting colors for a vibrant and dynamic result. The outcome will be unique, reflecting your current artistic sensibility. Abstract art is liberating because there is no wrong way to color it. Unlike figurative coloring pages where you might wonder 'should the sky be blue?', abstract art answers: color as you feel. This total freedom is particularly beneficial for adults who tend to self-censor artistically. Finished abstract coloring pages also make excellent decorative objects: framed, they create beautiful original artworks to decorate your home. Our abstract coloring pages are available for free in A4 format. Print them on quality paper for the best result and display your creations with pride.",
  },
  'category.cartes.seoText': {
    fr: "Explorez le monde depuis votre table grâce à nos coloriages cartes géographiques ! Notre collection propose des cartes illustrées du monde, des continents et des pays que les adultes et les enfants peuvent colorier pour apprendre la géographie de manière ludique et créative. Colorier une carte du monde est une expérience à la fois artistique et éducative. En donnant une couleur différente à chaque pays ou région, vous mémorisez naturellement leur emplacement et leurs frontières. C'est une méthode d'apprentissage par le faire, bien plus efficace que la simple lecture d'un atlas. Nos cartes illustrées intègrent des éléments décoratifs : boussoles, roses des vents et parfois des petites illustrations des productions typiques de chaque région. Ces détails rendent le coloriage de cartes particulièrement enrichissant et esthétiquement plaisant. Une carte du monde coloriée avec soin fait un magnifique poster éducatif pour la chambre d'un enfant ou un bureau d'adulte. Ces coloriages développent la curiosité géographique, l'intérêt pour les autres cultures et la conscience des réalités mondiales. Nos coloriages cartes sont disponibles gratuitement au format A4. Pour les cartes de grand format, assemblez plusieurs feuilles pour un rendu encore plus impressionnant et éducatif.",
    en: "Explore the world from your table with our geographical map coloring pages! Our collection features illustrated maps of the world, continents, and countries that adults and children can color to learn geography in a fun and creative way. Coloring a world map is both an artistic and educational experience. By giving different colors to each country or region, you naturally memorize their locations and borders. It's a learn-by-doing method, far more effective than simply reading an atlas. Our illustrated maps incorporate decorative elements: compasses, wind roses, and sometimes small illustrations of typical productions from each region. These details make map coloring particularly enriching and aesthetically pleasing. A carefully colored world map makes a beautiful educational poster for a child's room or an adult's office. These coloring pages develop geographical curiosity, interest in other cultures, and awareness of global realities. Our map coloring pages are available for free in A4 format. For large-format maps, assemble several sheets for an even more impressive and educational result.",
  },
  'category.paysages.seoText': {
    fr: "La montagne enneigée, la forêt mystérieuse, la plage au coucher du soleil, la campagne verdoyante : les paysages offrent une infinité de sources d'inspiration pour les artistes. Nos coloriages paysages pour adultes proposent des vues panoramiques de la nature sous tous ses aspects, des plus apaisants aux plus spectaculaires. Chaque paysage est soigneusement composé pour offrir un équilibre visuel satisfaisant : un premier plan détaillé, un milieu habité (arbre, maison, rivière) et un arrière-plan atmosphérique (ciel, horizon). Cette structure classique de la composition paysagère permet d'explorer les techniques de perspective et de rendu de la profondeur. Colorier un paysage invite à réfléchir à la lumière et à l'atmosphère : un paysage de matin aura des teintes froides et brumeuses, un coucher de soleil des orangés et des roses flamboyants, une forêt d'été une multitude de verts. Ces réflexions sur la couleur et la lumière développent la sensibilité artistique et la conscience visuelle. Les paysages terminés font de beaux décors pour la maison ou le bureau, rappelant des lieux aimés ou évoquant des voyages rêvés. Nos coloriages paysages sont disponibles gratuitement au format A4 haute résolution. Utilisez des aquarelles ou des crayons de couleur pour les effets de dégradé et les textures atmosphériques.",
    en: "Snow-capped mountains, mysterious forests, beaches at sunset, verdant countryside — landscapes offer an infinite source of inspiration for artists. Our adult landscape coloring pages feature panoramic views of nature in all its aspects, from the most soothing to the most spectacular. Each landscape is carefully composed to offer satisfying visual balance: a detailed foreground, a middle ground with life (tree, house, river), and an atmospheric background (sky, horizon). This classic landscape composition structure allows exploration of perspective techniques and depth rendering. Coloring a landscape invites reflection on light and atmosphere: a morning landscape has cool, misty tones; a sunset blazes with oranges and pinks; a summer forest offers a multitude of greens. These reflections on color and light develop artistic sensibility and visual awareness. Finished landscapes make beautiful decorations for the home or office, recalling beloved places or evoking dreamed-of travels. Our landscape coloring pages are available for free in A4 high-resolution format. Use watercolors or colored pencils for gradient effects and atmospheric textures.",
  },
};

export function t(key: string, locale: Locale): string {
  return translations[key]?.[locale] ?? key;
}

export function ti(key: string, locale: Locale, params: Record<string, string>): string {
  let result = t(key, locale);
  for (const [k, v] of Object.entries(params)) {
    result = result.replace(`{${k}}`, v);
  }
  return result;
}

export function getCategoryLabel(category: Category, locale: Locale): string {
  return t(`category.${category}`, locale);
}

export function getLocalePath(locale: Locale, path: string = ''): string {
  return `/${locale}${path}`;
}

const enSlugs: Record<Category, string> = {
  animaux: 'animals',
  vehicules: 'vehicles',
  nature: 'nature',
  alphabet: 'alphabet',
  dinosaures: 'dinosaurs',
  'super-heros': 'superheroes',
  espace: 'space',
  'princesses-chevaliers': 'princesses-knights',
  metiers: 'jobs',
  sport: 'sport',
  saisons: 'seasons',
  fetes: 'holidays',
  mandalas: 'mandalas',
  mosaiques: 'mosaics',
  abstrait: 'abstract',
  cartes: 'maps',
  personnages: 'characters',
  contes: 'fairy-tales',
  drole: 'funny',
  paysages: 'landscapes',
};

export function getCategorySlug(category: Category, locale: Locale): string {
  if (locale === 'en') {
    return enSlugs[category];
  }
  return category;
}

export function getColoringBasePath(locale: Locale): string {
  return locale === 'fr' ? 'coloriage' : 'coloring';
}

export function getPrivacyPath(locale: Locale): string {
  return getLocalePath(locale, locale === 'fr' ? '/confidentialite' : '/privacy');
}

export function getTermsPath(locale: Locale): string {
  return getLocalePath(locale, locale === 'fr' ? '/conditions' : '/terms');
}

export function getCategoriesPath(locale: Locale): string {
  return getLocalePath(locale, locale === 'fr' ? '/categories' : '/categories');
}
